var i=true,k=null,l=false;function r(){return function(){}}jQuery.S.jswing=jQuery.S.swing;
jQuery.extend(jQuery.S,{Jb:"easeOutQuad",Md:function(a,b,c,d,e){return jQuery.S[jQuery.S.Jb](a,b,c,d,e)},Tc:function(a,b,c,d,e){return d*(b/=e)*b+c},bd:function(a,b,c,d,e){return-d*(b/=e)*(b-2)+c},Pc:function(a,b,c,d,e){if((b/=e/2)<1)return d/2*b*b+c;return-d/2*(--b*(b-2)-1)+c},Gc:function(a,b,c,d,e){return d*(b/=e)*b*b+c},Zc:function(a,b,c,d,e){return d*((b=b/e-1)*b*b+1)+c},Mc:function(a,b,c,d,e){if((b/=e/2)<1)return d/2*b*b*b+c;return d/2*((b-=2)*b*b+2)+c},Uc:function(a,b,c,d,e){return d*(b/=e)*
b*b*b+c},cd:function(a,b,c,d,e){return-d*((b=b/e-1)*b*b*b-1)+c},Qc:function(a,b,c,d,e){if((b/=e/2)<1)return d/2*b*b*b*b+c;return-d/2*((b-=2)*b*b*b-2)+c},Vc:function(a,b,c,d,e){return d*(b/=e)*b*b*b*b+c},dd:function(a,b,c,d,e){return d*((b=b/e-1)*b*b*b*b+1)+c},Rc:function(a,b,c,d,e){if((b/=e/2)<1)return d/2*b*b*b*b*b+c;return d/2*((b-=2)*b*b*b*b+2)+c},Wc:function(a,b,c,d,e){return-d*Math.cos(b/e*(Math.PI/2))+d+c},ed:function(a,b,c,d,e){return d*Math.sin(b/e*(Math.PI/2))+c},Sc:function(a,b,c,d,e){return-d/
2*(Math.cos(Math.PI*b/e)-1)+c},Ic:function(a,b,c,d,e){return b==0?c:d*Math.pow(2,10*(b/e-1))+c},ad:function(a,b,c,d,e){return b==e?c+d:d*(-Math.pow(2,-10*b/e)+1)+c},Oc:function(a,b,c,d,e){if(b==0)return c;if(b==e)return c+d;if((b/=e/2)<1)return d/2*Math.pow(2,10*(b-1))+c;return d/2*(-Math.pow(2,-10*--b)+2)+c},Fc:function(a,b,c,d,e){return-d*(Math.sqrt(1-(b/=e)*b)-1)+c},Yc:function(a,b,c,d,e){return d*Math.sqrt(1-(b=b/e-1)*b)+c},Lc:function(a,b,c,d,e){if((b/=e/2)<1)return-d/2*(Math.sqrt(1-b*b)-1)+
c;return d/2*(Math.sqrt(1-(b-=2)*b)+1)+c},Hc:function(a,b,c,d,e){a=1.70158;var f=0,g=d;if(b==0)return c;if((b/=e)==1)return c+d;f||(f=e*0.3);if(g<Math.abs(d)){g=d;a=f/4}else a=f/(2*Math.PI)*Math.asin(d/g);return-(g*Math.pow(2,10*(b-=1))*Math.sin((b*e-a)*2*Math.PI/f))+c},$c:function(a,b,c,d,e){a=1.70158;var f=0,g=d;if(b==0)return c;if((b/=e)==1)return c+d;f||(f=e*0.3);if(g<Math.abs(d)){g=d;a=f/4}else a=f/(2*Math.PI)*Math.asin(d/g);return g*Math.pow(2,-10*b)*Math.sin((b*e-a)*2*Math.PI/f)+d+c},Nc:function(a,
b,c,d,e){a=1.70158;var f=0,g=d;if(b==0)return c;if((b/=e/2)==2)return c+d;f||(f=e*0.3*1.5);if(g<Math.abs(d)){g=d;a=f/4}else a=f/(2*Math.PI)*Math.asin(d/g);if(b<1)return-0.5*g*Math.pow(2,10*(b-=1))*Math.sin((b*e-a)*2*Math.PI/f)+c;return g*Math.pow(2,-10*(b-=1))*Math.sin((b*e-a)*2*Math.PI/f)*0.5+d+c},Ec:function(a,b,c,d,e,f){if(f==undefined)f=1.70158;return d*(b/=e)*b*((f+1)*b-f)+c},Xc:function(a,b,c,d,e,f){if(f==undefined)f=1.70158;return d*((b=b/e-1)*b*((f+1)*b+f)+1)+c},Jc:function(a,b,c,d,e,f){if(f==
undefined)f=1.70158;if((b/=e/2)<1)return d/2*b*b*(((f*=1.525)+1)*b-f)+c;return d/2*((b-=2)*b*(((f*=1.525)+1)*b+f)+2)+c},Lb:function(a,b,c,d,e){return d-jQuery.S.Pa(a,e-b,0,d,e)+c},Pa:function(a,b,c,d,e){return(b/=e)<1/2.75?d*7.5625*b*b+c:b<2/2.75?d*(7.5625*(b-=1.5/2.75)*b+0.75)+c:b<2.5/2.75?d*(7.5625*(b-=2.25/2.75)*b+0.9375)+c:d*(7.5625*(b-=2.625/2.75)*b+0.984375)+c},Kc:function(a,b,c,d,e){if(b<e/2)return jQuery.S.Lb(a,b*2,0,d,e)*0.5+c;return jQuery.S.Pa(a,b*2-e,0,d,e)*0.5+d*0.5+c}});
(function(a){function b(e,f,g){f="("+g.replace(d,"\\$1")+")";return e.replace(RegExp(f,"gi"),"<strong>$1</strong>")}function c(e,f){this.j=a(e);this.j.d("autocomplete","off");this.m=[];this.data=[];this.ra=[];this.selectedIndex=-1;this.N=this.j.q();this.Za=0;this.Ja=[];this.xa=k;this.ua=l;this.pb=f.pb;this.ab=l;this.options={Bb:l,Xb:1,maxHeight:300,Ka:0,width:0,nd:i,ib:{},Nb:b,La:k,vd:l,zIndex:9999};this.Sb();this.lc(f)}var d=RegExp("(\\/|\\.|\\*|\\+|\\?|\\||\\(|\\)|\\[|\\]|\\{|\\}|\\\\)","g");a.kd.zc=
function(e){return new c(this.X(0)||a("<input />"),e)};c.prototype={va:k,Sb:function(){var e,f,g;e=this;f=Math.floor(Math.random()*1048576).toString(16);g="Autocomplete_"+f;this.va=function(h){if(a(h.target).ec(".autocomplete").size()===0){e.Ub();e.Kb()}};if(!this.options.width)this.options.width=this.j.width();this.wa="AutocompleteContainter_"+f;a('<div id="'+this.wa+'" style="position:absolute;z-index:9999;"><div class="autocomplete-w1"><div class="autocomplete" id="'+g+'" style="display:none; width:300px;"></div></div></div>').Ha("body");
this.I=a("#"+g);this.Sa();window.opera?this.j.rd(function(h){e.eb(h)}):this.j.qd(function(h){e.eb(h)});this.j.sd(function(h){e.cc(h)});this.j.blur(function(){e.Mb()});this.j.focus(function(){e.Sa()})},lc:function(e){var f=this.options;a.extend(f,e);if(f.ma){this.ab=i;if(a.$a(f.ma))f.ma={m:f.ma,data:[]}}a("#"+this.wa).a({zIndex:f.zIndex});this.I.a({maxHeight:f.maxHeight+"px",width:f.width})},Sa:function(){var e=this.j.Cd();if(t){f=this.j.parent().position().top+this.j.height()+60;e=e.left-10}else{var f=
this.j.parent().position().top+this.j.height()+63;e=e.left-10}a("#"+this.wa).a({top:f+this.j.innerHeight()+"px",left:e+"px"})},Mb:function(){a(document).H("click",this.va)},Kb:function(){a(document).L("click",this.va)},Ub:function(){var e=this;this.ub();this.Za=window.setInterval(function(){e.e();e.ub()},300)},ub:function(){window.clearInterval(this.Za)},eb:function(e){if(!(this.disabled||!this.enabled)){switch(e.keyCode){case 27:this.j.q(this.N);this.e();break;case 9:case 13:if(this.selectedIndex===
-1){this.e();return}this.select(this.selectedIndex);if(e.keyCode===9)return;break;case 38:this.$b();break;case 40:this.Zb();break;default:return}e.Ld();e.preventDefault()}},cc:function(e){if(!this.disabled){switch(e.keyCode){case 38:case 40:return}clearInterval(this.xa);if(this.N!==this.j.q())if(this.options.Ka>0){var f=this;this.xa=setInterval(function(){f.gb()},this.options.Ka)}else this.gb()}},gb:function(){clearInterval(this.xa);this.N=this.j.q();var e=this.ta(this.N);this.selectedIndex=-1;if(this.ua)this.ua=
l;else e===""||e.length<this.options.Xb?this.e():this.Ob(e)},ta:function(e){var f;f=this.options.La;if(!f)return a.wb(e);e=e.split(f);return a.wb(e[e.length-1])},Pb:function(e){var f,g,h,m,p;g=this.options.ma;h=g.m.length;f={m:[],data:[]};e=e.toLowerCase();for(p=0;p<h;p++){m=g.m[p];if(m.toLowerCase().indexOf(e)===0){f.m.push(m);f.data.push(g.data[p])}}return f},Ob:function(e){var f,g;if((f=this.ab?this.Pb(e):this.Ja[e])&&a.$a(f.m)){this.m=f.m;this.data=f.data;this.vb()}else if(!this.Tb(e)){g=this;
g.options.ib.ya=e;a.X(this.pb,g.options.ib,function(h){g.ic(h)},"text")}},Tb:function(e){for(var f=this.ra.length;f--;)if(e.indexOf(this.ra[f])===0)return i;return l},e:function(){this.enabled=l;this.selectedIndex=-1;this.I.e()},vb:function(){if(this.m.length===0)this.e();else{var e,f,g,h,m,p,y,w;e=this;f=this.m.length;h=this.options.Nb;m=this.ta(this.N);y=function(q){return function(){e.Ea(q)}};w=function(q){return function(){e.select(q)}};this.I.e().empty();for(p=0;p<f;p++){g=this.m[p];g=a((e.selectedIndex===
p?'<div class="selected"':"<div")+' title="'+g+'">'+h(g,this.data[p],m)+"</div>");g.yd(y(p));g.click(w(p));this.I.append(g)}this.enabled=i;this.I.show()}},ic:function(e){var f;try{f=eval("("+e+")")}catch(g){return}if(!a.$a(f.data))f.data=[];if(!this.options.zd){this.Ja[f.ya]=f;f.m.length===0&&this.ra.push(f.ya)}if(f.ya===this.ta(this.N)){this.m=f.m;this.data=f.data;this.vb()}},Ea:function(e){var f,g;f=this.I.l();this.selectedIndex!==-1&&f.length>this.selectedIndex&&a(f.X(this.selectedIndex)).n();
this.selectedIndex=e;if(this.selectedIndex!==-1&&f.length>this.selectedIndex){g=f.X(this.selectedIndex);a(g).o("selected")}return g},select:function(e){var f;if(f=this.m[e]){this.j.q(f);if(this.options.Bb){f=this.j.ec("form");f.length>0&&f.X(0).submit()}this.ua=i;this.e();this.fb(e)}},$b:function(){if(this.selectedIndex!==-1)if(this.selectedIndex===0){this.I.l().X(0).className="";this.selectedIndex=-1;this.j.q(this.N)}else this.Fa(this.selectedIndex-1)},Zb:function(){this.selectedIndex!==this.m.length-
1&&this.Fa(this.selectedIndex+1)},Fa:function(e){var f,g,h;f=this.Ea(e).offsetTop;g=this.I.scrollTop();h=g+this.options.maxHeight-25;if(f<g)this.I.scrollTop(f);else f>h&&this.I.scrollTop(f-this.options.maxHeight+25);this.j.q(this.Ua(this.m[e]))},fb:function(e){var f,g;f=this.options.fb;g=this.m[e];e=this.data[e];this.j.q(this.Ua(g));a.pd(f)&&f(g,e,this.j)},Ua:function(e){var f,g;f=this.options.La;if(!f)return e;g=this.N;f=g.split(f);if(f.length===1)return e;return g.substr(0,g.length-f[f.length-1].length)+
e}}})(jQuery);
(function(){function a(j,o){var s;this.element=typeof j=="object"?j:document.getElementById(j);this.k=this.element.parentNode;this.element.style.Qd="-webkit-transform";this.element.style.Rd="cubic-bezier(0,0,0.25,1)";this.element.style.ha="0";this.element.style.xb=y+"0,0"+w;this.options={Bc:c,Yb:c,Cb:i,Nd:l,Qb:c,rc:c,la:d||e||!g,sb:d||e||!g,Ma:l,overflow:"hidden",Aa:l,hb:k,sc:i};if(typeof o=="object")for(s in o)this.options[s]=o[s];if(this.options.Ma)this.options.overflow="hidden";this.k.style.overflow=this.options.overflow;
this.lb();window.addEventListener("onorientationchange"in window?"orientationchange":"resize",this,l);if(g||this.options.Ma){this.element.addEventListener(h,this,l);this.element.addEventListener(m,this,l);this.element.addEventListener(p,this,l)}this.options.Cb&&this.element.addEventListener("DOMSubtreeModified",this,l)}function b(j,o,s,z){this.dir=j;this.hd=s;this.rb=z;this.Ba=++q;this.V=document.createElement("div");j="position:absolute;top:0;left:0;-webkit-transition-timing-function:cubic-bezier(0,0,0.25,1);pointer-events:none;-webkit-transition-duration:0;-webkit-transition-delay:0;-webkit-transition-property:-webkit-transform;z-index:10;background:rgba(0,0,0,0.5);-webkit-transform:"+
y+"0,0"+w+";"+(j=="horizontal"?"-webkit-border-radius:3px 2px;min-width:6px;min-height:5px":"-webkit-border-radius:2px 3px;min-width:5px;min-height:6px");this.V.setAttribute("style",j);this.k=document.createElement("div");j="-webkit-mask:-webkit-canvas(scrollbar"+this.Ba+this.dir+");position:absolute;z-index:10;pointer-events:none;overflow:hidden;opacity:0;-webkit-transition-duration:"+(s?"300ms":"0")+";-webkit-transition-delay:0;-webkit-transition-property:opacity;"+(this.dir=="horizontal"?"bottom:2px;left:2px;right:7px;height:5px":
"top:2px;right:2px;bottom:7px;width:5px;");this.k.setAttribute("style",j);this.k.appendChild(this.V);o.appendChild(this.k)}a.prototype={x:0,y:0,enabled:i,lb:function(){var j=this.x,o=this.y;this.scrollWidth=this.k.clientWidth;this.scrollHeight=this.k.clientHeight;this.za=this.element.offsetWidth;this.na=this.element.offsetHeight;this.O=this.scrollWidth-this.za;this.K=this.scrollHeight-this.na;this.Oa=this.Na=0;if(this.scrollX)if(this.O>=0)j=0;else if(this.x<this.O)j=this.O;if(this.scrollY)if(this.K>=
0)o=0;else if(this.y<this.K)o=this.K;if(this.options.Aa){this.Vb=-Math.floor(this.O/this.scrollWidth);this.Wb=-Math.floor(this.K/this.scrollHeight);o=this.Aa(j,o);j=o.x;o=o.y}if(j!=this.x||o!=this.y){this.qb("0");this.ea(j,o,i)}this.scrollX=this.za>this.scrollWidth;this.scrollY=!this.scrollX||this.na>this.scrollHeight;if(this.options.Qb&&this.scrollX){this.w=this.w||new b("horizontal",this.k,this.options.la,this.options.sb);this.w.Xa(this.scrollWidth,this.za)}else if(this.w)this.w=this.w.remove();
if(this.options.rc&&this.scrollY&&this.na>this.scrollHeight){this.z=this.z||new b("vertical",this.k,this.options.la,this.options.sb);this.z.Xa(this.scrollHeight,this.na)}else if(this.z)this.z=this.z.remove()},ea:function(j,o,s){this.x=j;this.y=this.options.sc?o:0;this.element.style.xb=y+this.x+"px,"+this.y+"px"+w;if(!s){this.w&&this.w.ea(this.x);this.z&&this.z.ea(this.y)}},qb:function(j){j=j||"0";this.element.style.ha=j;if(this.w){this.w.V.style.ha=j;this.w.k.style.ha=c&&this.options.la?"300ms":"0"}if(this.z){this.z.V.style.ha=
j;this.z.k.style.ha=c&&this.options.la?"300ms":"0"}},ob:function(){var j=this.x,o=this.y;if(this.x>=0)j=0;else if(this.x<this.O)j=this.O;if(this.y>=0||this.K>0)o=0;else if(this.y<this.K)o=this.K;if(j!=this.x||o!=this.y)this.scrollTo(j,o);else{if(this.db){this.dc();this.db=l}this.w&&this.w.e();this.z&&this.z.e()}},Aa:function(j,o){j=this.Na>0?Math.floor(j/this.scrollWidth):this.Na<0?Math.ceil(j/this.scrollWidth):Math.round(j/this.scrollWidth);this.pageX=-j;j*=this.scrollWidth;if(j>0)j=this.pageX=0;
else if(j<this.O){this.pageX=this.Vb;j=this.O}o=this.Oa>0?Math.floor(o/this.scrollHeight):this.Oa<0?Math.ceil(o/this.scrollHeight):Math.round(o/this.scrollHeight);this.pageY=-o;o*=this.scrollHeight;if(o>0)o=this.pageY=0;else if(o<this.K){this.pageY=this.Wb;o=this.K}return{x:j,y:o,oc:Math.round(Math.max(Math.abs(this.x-j)/this.scrollWidth*500,Math.abs(this.y-o)/this.scrollHeight*500))}},scrollTo:function(j,o,s){if(this.x==j&&this.y==o)this.ob();else{this.db=i;this.qb(s||"350ms");this.ea(j,o);s==="0"||
s=="0s"||s=="0ms"?this.ob():document.addEventListener("webkitTransitionEnd",this,l)}},Yb:function(j,o,s,z){o=Math.abs(j)/o*1E3;var n=o*o/2.5/1E3,A=0;if(j>0&&n>s){o=o*s/n/2.5;n=s}else if(j<0&&n>z){o=o*z/n/2.5;n=z}n*=j<0?-1:1;A=o/1.2;return{Dc:Math.round(n),oc:Math.round(A)}},dc:function(){if(this.y-$(window).height()/3<=this.K){this.lb();this.options.hb&&this.options.hb()}}};b.prototype={Xa:function(j,o){var s;if(this.dir=="horizontal"){if(this.t!=this.k.offsetWidth){this.t=this.k.offsetWidth;s=document.getCSSCanvasContext("2d",
"scrollbar"+this.Ba+this.dir,this.t,5);s.fillStyle="rgb(0,0,0)";s.beginPath();s.arc(2.5,2.5,2.5,Math.PI/2,-Math.PI/2,l);s.lineTo(this.t-2.5,0);s.arc(this.t-2.5,2.5,2.5,-Math.PI/2,Math.PI/2,l);s.closePath();s.fill()}}else if(this.t!=this.k.offsetHeight){this.t=this.k.offsetHeight;s=document.getCSSCanvasContext("2d","scrollbar"+this.Ba+this.dir,5,this.t);s.fillStyle="rgb(0,0,0)";s.beginPath();s.arc(2.5,2.5,2.5,Math.PI,0,l);s.lineTo(5,this.t-2.5);s.arc(2.5,this.t-2.5,2.5,0,Math.PI,l);s.closePath();s.fill()}this.size=
Math.max(Math.round(this.t*this.t/o),6);this.Y=this.t-this.size;this.pc=this.Y/(j-o);this.V.style[this.dir=="horizontal"?"width":"height"]=this.size+"px"},ea:function(j){this.k.style.opacity!="1"&&this.show();j=Math.round(this.pc*j);if(j<0){j=this.rb?j+j*3:0;if(this.size+j<7)j=-this.size+6}else if(j>this.Y){j=this.rb?j+(j-this.Y)*3:this.Y;if(this.size+this.Y-j<7)j=this.size+this.Y-6}j=this.dir=="horizontal"?y+j+"px,0"+w:y+"0,"+j+"px"+w;this.V.style.xb=j},show:function(){if(c)this.k.style.uc="0";this.k.style.opacity=
"1"},e:function(){if(c)this.k.style.uc="350ms";this.k.style.opacity="0"},remove:function(){this.k.parentNode.removeChild(this.k);return k}};var c="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix,d=/iphone/gi.test(navigator.appVersion),e=/ipad/gi.test(navigator.appVersion),f=/android/gi.test(navigator.appVersion),g=d||e||f,h=g?"touchstart":"mousedown",m=g?"touchmove":"mousemove",p=g?"touchend":"mouseup",y="translate"+(c?"3d(":"("),w=c?",0)":")",q=0;window.od=a})();
var aa="webkit",ba="android",ca="iphone",da="ipod",ea="macintosh",fa="nuvifone",ga="symbian",ha="series60",ia="series70",ja="series80",ka="series90",la="windows ce",ma="windows",na="iemobile",oa="ppc",qa="wm5 pie",ra="blackberry",sa="vnd.rim",ta="palm",ua="webos",va="blazer",wa="xiino",t="mobile",xa="htc",u=navigator.userAgent.toLowerCase();function ya(){return u.search(aa)>-1?i:l}
function za(){if(u.search(la)>-1||u.search(na)>-1||u.search(qa)>-1)return i;if(u.search(oa)>-1&&!(u.search(ea)>-1))return i;return u.search(xa)>-1&&u.search(ma)>-1?i:l}
function Aa(){if(u.search(ca)>-1||u.search(da)>-1?i:l)return i;if(ya()?u.search(ha)>-1||u.search(ga)>-1?i:l:l)return i;if(u.search(ga)>-1||u.search(ha)>-1||u.search(ia)>-1||u.search(ja)>-1||u.search(ka)>-1?i:l)return i;if(za())return i;if(u.search(ba)>-1?i:l)return i;var a;a=u.search(ra)>-1?i:u.search(sa)>-1?i:l;if(a)return i;if(u.search(ua)>-1?i:l)return i;if(u.search(ta)>-1||u.search(va)>-1||u.search(wa)>-1?(u.search(ua)>-1?i:l)?l:i:l)return i;if(u.search(fa)>-1?i:l)return i;return l}
$(document).Fd(function(){$("#back").click(function(){window.location.hash!=="#"&&window.location.hash!==""&&window.location.hash!=="#/"&&window.location.hash!=k&&window.history.back()});$("#home").click(function(){v=x=B=C="";if(D=="main"&&E!="wall")$("#wall_view").click();else{E="wall";Ba()}});$("#settings").click(function(){window.location.hash="/settings";typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Settings","Shown",""])});$("#give_feedback a").c("click",Ca);$("#feedback_cont").click(function(){return l});
$("#submit_feedback").click(function(){var a=$("#feedback_message").q();a!=""?$.P("/submit_feedback/",{message:a},function(){$("#feedback_message").q("");$("#feedback_cont_wrap").e();$("#feedback_reponse").show()}):$("#error_text").text("We need at least a few letters to know how you feel.")});$(document).H("keyup",function(a){a=a.keyCode;if(a!==13)if(a===39)if(D=="album"){Ea();Fa()}else if(D=="info")Ga();else if(D==="gallery")$("#forward_gallery, #forward_gallery_mobile").click();else D=="nom_detail"&&
$(".next_photo").click();else if(a===37)if(D=="profile")Ga();else if(D=="album"){Ha();Ia()}else if(D=="gallery")$("#back_gallery, #back_gallery_mobile").click();else D=="nom_detail"&&$(".prev_photo").click();else if(a===27)Ja();else{String.fromCharCode(a);Ka===l&&a<=90&&a>=48&&F===l&&G!==k&&La()}});$("#search_cont").click(function(a){a.stopPropagation()});$("#search_control").click(function(a){a.stopPropagation();$("#close_search").n().o("close_img "+H);La()});$("#close_search").click(function(){Ja()});
$("#logout").H("click",function(){FB.ud(function(){if(window.sessionStorage!==undefined){sessionStorage.clear();sessionStorage.clear()}window.location.href="/"});$("#cont").ca("fast",function(){$(this).h("");$("#cont").s("fast").append('<div id="logout_cont"><div id="loader"><img src="http://s3.amazonaws.com/portrit/img/album-loader-dark.gif"/></div><h1>Logging out. Hold on to your butts!</h1></div>')})})});
Array.prototype.remove=function(a,b){var c=this.slice((b||a)+1||this.length);this.length=a<0?this.length+a:a;return this.push.apply(this,c)};if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,b){if(b==k)b=0;else if(b<0)b=Math.max(0,this.length+b);var c=0,d=0;c=b;for(d=this.length;c<d;c++)if(this[c]===a)return c;return-1};Array.prototype.remove=function(a,b){var c=this.slice((b||a)+1||this.length);this.length=a<0?this.length+a:a;return this.push.apply(this,c)};jQuery.bb=0;
jQuery.extend(jQuery.gd[":"],{random:function(a,b,c,d){if(b==0)jQuery.bb=Math.floor(Math.random()*d.length);return b==jQuery.bb}});function I(){for(var a={},b=window.location.hash.split("/"),c=k,d=0;d<b.length;d++){c=b[d].split("=");if(c.length>0)for(var e=0;e<c.length;e++)a[c[0]]=c[1]==undefined?"":c[1];else a[b[d]]=""}return a}
function J(a){a=Number(a);var b=Math.floor(a/86400),c=Math.floor(a/3600),d=Math.floor(a%3600/60);a=Math.floor(a%3600%60);return b>1?b+" Days ago":b==1?b+" Day ago":c>1?c+" Hours ago":c==1?c+" Hour ago":d>1?d+" Minutes ago":d==1?d+" Minute ago":a>=10?a+" Seconds ago":"Right now"}function Ma(a){var b=["th","st","nd","rd"],c=a%100;return a+(b[(c-20)%10]||b[c]||b[0])}
var Na=k,K=k,Oa=k,Pa=k,C="",B="",x="",D="",v="",L=t=l,Qa=k,Ra=k,G=k,M={},Sa=100,F=l,Ta=l,Ua=l,N=[],Ka=l,O=k,P=k,Q=[],Va=[],Wa=k,E=k,R=k,Xa=k,S={},H="normal",U=k;
if(function(){if(u.search("ipad")>-1&&ya()?i:l)return l;if(Aa())return i;if(u.search("midp")>-1||(u.search("brew")>-1?i:l))return i;if(u.search("opera")>-1?u.search("mini")>-1||u.search("mobi")>-1?i:l:l)return i;if(u.search("netfront")>-1)return i;if(u.search("up.browser")>-1)return i;if(u.search("openweb")>-1)return i;if(u.search("danger")>-1||u.search("hiptop")>-1?i:l)return i;var a;a=u.search("maemo")>-1?i:u.search("tablet")>-1&&u.search("linux")?i:l;if(a)return i;if(u.search("archos")>-1?i:l)return i;
if(u.search("pda")>-1)return i;if(u.search(t)>-1)return i;if(u.search("kindle")>-1?i:l)return i;return l}()===i){t=i;H="mobile";var Ya=typeof _gaq!=="undefined"?'<link rel="stylesheet" href="http://s3.amazonaws.com/portrit/styles/production/mobile_landing.css"/><link rel="stylesheet" href="http://s3.amazonaws.com/portrit/styles/production/mobile.css"/><meta id="viewport_meta" name="viewport" content="width=520, user-scalable=no"/><link rel="shortcut icon" href="http://s3.amazonaws.com/portrit/img/favicon.ico"><link rel="apple-touch-icon" href="http://s3.amazonaws.com/portrit/img/icon128.png"/><link rel="apple-touch-icon-precomposed" href="http://s3.amazonaws.com/portrit/img/icon128.png"/>':
'<link rel="stylesheet" href="http://s3.amazonaws.com/portrit/styles/trunk/mobile_landing.css"/><link rel="stylesheet" href="http://s3.amazonaws.com/portrit/styles/trunk/mobile.css"/><meta id="viewport_meta" name="viewport" content="width=520, user-scalable=no"/><link rel="shortcut icon" href="http://s3.amazonaws.com/portrit/img/favicon.ico"><link rel="apple-touch-icon" href="http://s3.amazonaws.com/portrit/img/icon128.png"/><link rel="apple-touch-icon-precomposed" href="http://s3.amazonaws.com/portrit/img/icon128.png"/>';
$("head").append(Ya);var Za=520;$("body, html, #header, #cont, #wrapper").a({margin:"0 auto","min-width":Za,width:Za,"max-width":Za});if(window.orientation!=0){Za=720;$("#viewport_meta").d("content","width=520, user-scalable=no, target-densityDpi=160")}else{Za=520;$("#viewport_meta").d("content","width=520, user-scalable=no, target-densityDpi=260")}}else if((u.search("ipad")>-1&&ya()?i:l)===i){H="mobile";L=t=i}
function Ba(){var a="",b="",c="",d="",e=i;if(C!==""){a="user="+C;e=l}if(B!==""){b="/album="+B;e=l}if(x!==""){c="/gallery";e=l}if(e===i)if(v==="wall")d="display="+v;else if(v==="alpha")d="display="+v;window.location.hash="#/"+d+a+b+c}
function Ca(a){F=i;a.stopPropagation();t?$("#wrapper").a({opacity:"0.3"}):$("#wrapper").G({opacity:"0.3"},200);$("#feedback_cont_wrap").show();$("#feedback_reponse").e();$("#feedback").show();$("#feedback_message").focus();$(document).H("click",$a);$("#close_feedback").n().o("close_img "+H);$("#close_feedback, #close_feedback_button").H("click",$a);return l}
function $a(){F=l;if(t){$("#wrapper").a({opacity:"1.0"});$("#feedback").e()}else{$("#wrapper").G({opacity:1},300);$("#feedback").ca()}$(document).L("click",$a);$("#close_feedback, #close_feedback_button").L("click",$a)}var ab,V,bb,cb=k,db=k;function eb(){cb.removeEventListener("touchmove",fb);cb.removeEventListener("touchend",gb);bb=startY=ab=k}
function fb(a){if(a.touches.length>1)eb();else{V=a.touches[0].pageX-ab;a=a.touches[0].pageY-startY;if(bb==k)bb=V;else if(bb<0&&V>0||bb>0&&V<0||Math.abs(a)>100)eb()}}function gb(){eb();if(Math.abs(V)>200)db({target:cb,direction:V>0?"right":"left"})}function hb(a){if(a.touches.length==1){V=0;ab=a.touches[0].pageX;startY=a.touches[0].pageY;cb.addEventListener("touchmove",fb,i);cb.addEventListener("touchend",gb,l)}}var ib=k,jb=k;
$(".notification_popup").c("click",function(){var a=this,b=$(this).d("value");window.location.href="#/nom_id="+b;$(this).a({opacity:0});setTimeout(function(){$(a).remove()},350)});t||$(".notification_popup").c("mouseover mouseout",function(a){var b=this;if(a.type=="mouseover"){clearTimeout(ib);clearTimeout(jb)}else ib=setTimeout(function(){$(b).a({opacity:0});jb=setTimeout(function(){$(b).remove()},350)},7500)});
$(".close_notification").c("click",function(a){var b=$(this).parent();$(b).a({opacity:0});setTimeout(function(){$(b).remove()},350);a.stopPropagation();return l});$(".notification_popup_cont").c("click",function(){var a=$(this).d("value"),b=$(this).d("read"),c=$(this).d("won"),d="",e=$(this).d("id").replace("notification_","");b=="0"&&$.P("/notification_read/",{notification_id:e},r());if(c)d="/won";window.location.href="#/nom_id="+a+d});
$(".notification_popup_cont").c("mouseover mouseout",function(a){var b=$(this).d("name");if(a.type=="mouseover"){$(this).o("nom_cat_"+b).n("color_transition");$(this).a({color:"white"});$(this).find("p").a({color:"white"});$(this).find(".kill_notification").show()}else{$(this).n("nom_cat_"+b);$(this).a({color:""});$(this).find("p").a({color:""});$(this).find(".kill_notification").e()}});
$(".kill_notification").c("click",function(a){$(this).parent().d("read");var b=$(this).d("value");$.P("/notification_read/",{notification_id:b},r());$(this).parent().remove();a.stopPropagation();return l});
$("#clear_all_notifications").c("click",function(a){var b="";$(".notification_popup_cont").W(function(){if($(this).d("read")=="0")b+=$(this).d("id").replace("notification_","")+","});b!=""&&$.P("/notification_read/",{notification_ids:b},r());$(".notification_popup_cont").remove();a.stopPropagation();return l});var kb=l;
$("#footer_notification_cont").c("click",function(){if(kb){$("#wrapper").b("click");$("#clear_all_notifications").e();$("#footer").a({"overflow-y":"hidden"});$(this).a({opacity:"0.3"});$("#notification_popup").show().a({opacity:"0.0"});t?$("#notification_footer_popup").e():$("#notification_footer_popup").ca("fast");kb=l}else{$(this).a({opacity:"1.0"});$(this).l().filter("p").d("class","");$("#footer").a({"overflow-y":"visible"});t?$("#notification_footer_popup").show():$("#notification_footer_popup").s("fast");
$("#notification_popup").show().a({opacity:"1.0"});var a=$('.notification_popup_cont[read="false"]');a.length>0&&setTimeout(function(){$(a).W(function(){var e=$(this).d("name");$(this).n("nom_cat_"+e)})},100);var b=new Date,c=k,d=k;$(".notification_popup_cont").W(function(){d=$(this).d("time");d=new Date(d*1E3);c=b-d;c/=1E3;time_str=J(parseInt(c));$(this).find(".time").text(" - "+time_str)});$(".notification_popup_cont").length>5&&$("#clear_all_notifications").show();$("#wrapper").c("click",function(){kb=
i;$("#footer_notification_cont").click()});kb=i}});var lb=k;function La(){Ka=i;if(t){$("#search").show();$("#wrapper").a({opacity:"0.3"});$("#query").focus()}else{$("#search").s();$("#wrapper").G({opacity:"0.3"},350,function(){$("#query").focus()})}typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Search","Shown",""]);$(document).H("click",Ja)}
function Ja(){$(document).L("click",Ja);$(".autocomplete").e();if(t){$("#search").e();$("#wrapper").a({opacity:"1.0"})}else{$("#search").ca();$("#wrapper").G({opacity:"1.0"},350)}$(".autocomplete").l().remove();$("#query").q("");Ka=l}
function mb(a,b,c,d,e,f,g){if(window.sessionStorage!==undefined)var h=sessionStorage.getItem("albums_"+a);if(h===k||h==="")FB.aa("/"+a+"/albums?fields=count,id,name",function(m){function p(z){y===l&&$.J(z.Ed.next+"&callback=?",function(n){if(n.data.length>0){p(n);w=i;if(n.data.length>0)o+=",";for(var A=0;A<n.data.length;A++){q.push({album:n.data[A],photos:k});j=n.data[A].id;o+=A<n.data.length-1?j+",":j}}else{if(w===l){if(n.data.length>0)o+=",";for(A=0;A<n.data.length;A++){q.push({album:n.data[A],
photos:k});j=n.data[A].id;o+=A<n.data.length-1?j+",":j}}y=i;if(window.sessionStorage!==undefined)sessionStorage["albums_"+a]=JSON.stringify(q);FB.aa("/"+a+"/photos?fields=height,width,picture,source,id&limit="+b,function(T){q=JSON.parse(sessionStorage.getItem("albums_"+a));q[0].u=q[0].u.concat(T.data);sessionStorage.setItem("albums_"+a,JSON.stringify(q));nb(T.data)});if(q.length>0)FB.aa("/photos/?fields=height,width,picture,source,id&limit="+b+"&ids="+o,function(T){C=a;q=JSON.parse(sessionStorage.getItem("albums_"+
a));for(var Da in T)if(Da!=="error")for(var Vb=T[Da],Wb=Da,pa=0;pa<q.length;pa++)if(q[pa].ia.id===Wb)q[pa].u=Vb.data;window.sessionStorage!==undefined&&sessionStorage.setItem("albums_"+a,JSON.stringify(q));if(c!==undefined){if(f===i){K=q;setTimeout(c,g)}else if(e){K=q;c(d,offset)}else{K=q;c(d)}ob()}});else{K=q;c(d);ob()}}})}var y=l,w=l;if(m.data==undefined)return l;var q=[],j=k,o="";q.push({album:{id:"tagged",name:"Tagged Pictures"},photos:[]});for(var s=0;s<m.data.length;s++){q.push({album:m.data[s],
photos:k});j=m.data[s].id;o+=s<m.data.length-1?j+",":j}if(m.data.length>0)p(m);else{K=q;c(d);ob()}});else{K=JSON.parse(h);if(K[0].u==k||K[0].u==l||K[0].u.length==0)FB.aa("/"+a+"/photos?fields=height,width,picture,source,id&limit="+b,function(m){h=JSON.parse(sessionStorage.getItem("albums_"+a));h[0].u=h[0].u.concat(m.data);sessionStorage.setItem("albums_"+a,JSON.stringify(h));nb(m.data)});if(c!==undefined){f===i?setTimeout(c,g):c(d);ob()}}}
function pb(a,b){FB.aa("/"+a+"/videos/",function(c){O=c.data;b!==undefined&&b()})}if(t){$(".main_control").c("touchend",qb);$("#friend_view").c("touchend",rb);$("#wall_view").c("touchend",sb);$("#profile_view").c("touchend",tb);$("#top_noms").c("touchend",ub);$("#recent_noms").c("touchend",vb)}else{$(".main_control").c("click",qb);$("#friend_view").c("click",rb);$("#wall_view").c("click",sb);$("#profile_view").c("click",tb);$("#top_noms").c("click",ub);$("#recent_noms").c("click",vb)}
function qb(){$(".main_control_active").n("main_control_active");$(this).o("main_control_active")}function rb(){if(E!="friend"){E="friend";sessionStorage.removeItem("default_view");sessionStorage.setItem("default_view",JSON.stringify(E));if(window.location.hash=="#/"||window.location.hash=="#"||window.location.hash==""){var a=I();wb(a);xb();yb();zb();$("html, body").scrollTop(0)}else window.location.hash="#/"}}
function sb(){if(E!="wall"){E="wall";sessionStorage.removeItem("default_view");sessionStorage.setItem("default_view",JSON.stringify(E));if(window.location.hash=="#/"||window.location.hash=="#"||window.location.hash==""){var a=I();wb(a);xb();Ab();zb();$("html, body").scrollTop(0)}else window.location.hash="#/"}}
function tb(){if(E!="profile"){E="profile";sessionStorage.removeItem("default_view");sessionStorage.setItem("default_view",JSON.stringify(E));if(window.location.hash=="#/"||window.location.hash=="#"||window.location.hash==""){var a=I();wb(a);xb();zb();$("html, body").scrollTop(0)}else window.location.hash="#/"}}
function ub(){if(R!="top_noms"){R="top_noms";sessionStorage.removeItem("stream_view");sessionStorage.setItem("stream_view",JSON.stringify(R));$("#recent_noms").n("selected");$(this).o("selected");$("#profile_cont_wrap").h('<div id="scroller"><div id="profile_cont"></div></div>');zb();$("html, body").scrollTop(0);typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Top Noms","Click",""])}}
function vb(){if(R!="recent_noms"){R="recent_noms";sessionStorage.removeItem("stream_view");sessionStorage.setItem("stream_view",JSON.stringify(R));$("#top_noms").n("selected");$(this).o("selected");$("#profile_cont_wrap").h('<div id="scroller"><div id="profile_cont"></div></div>');zb();$("html, body").scrollTop(0);typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Recent Noms","Shown",""])}}
function zb(){D="main";Qa=k;B=C="";K=k;M={};$("#main_view_control").remove();var a="",b="",c="";if(E=="friend")a="main_control_active";else if(E=="wall")b="main_control_active";else if(E=="profile")c="main_control_active";a='<div id="main_view_control"><a id="friend_view" class="main_control awesome large '+a+'">Friends</a><a id="wall_view" class="main_control awesome large '+b+' ">Stream</a><a id="profile_view" class="main_control awesome large '+c+'">Profile</a></div>';$("#cont").hc(a);if(E==="friend"){$("#wall_cont").e();
var d=b="";b="";d=l;c="";Va=[];for(a=0;a<Q.length;a++)if(Q[a].Rb===l){b="";if(Va[Q[a].name[0]]===undefined){Va[Q[a].name[0]]=[];Va[Q[a].name[0]].push(Q[a]);d=i;c="has_alpha"}else{Va[Q[a].name[0]].push(Q[a]);d=l;c="no_alpha"}if(d===i)b='<h1 class="alpha_key_wall" id="alpha_wall_'+Q[a].name[0]+'" onclick="void(0)">'+Q[a].name[0]+"</h1>";if(d){d='<div class="crop"><img class="friend_pic" src="https://graph.facebook.com/'+Q[a].id+'/picture?type=large"/></div>';b='<div class="friend '+c+'" name="'+Q[a].name+
'" value="'+Q[a].id+'" onclick="void(0)">'+b+'<div class="img_cont">'+d+"</div></div>";$("#wall_cont").append(b)}}$("#friend_cont").append('<div class="clear"></div>');if(t)$("#wall_cont").show();else{$("#wall_cont").a({"max-width":"960px"});$("#wall_cont").s(300)}}else if(E==="wall"){$("#user_profile_cont").remove();$(".friend").remove();if($("#wall_cont #profile_wrap").length==0){$("#wall_cont").e();a='<div id="profile_wrap"><div id="tab_nav"><div id="activate_recent_winners">Recent Winners</div><div id="activate_latest_photos">Latest Photos</div></div><ul><h1 id="active_stream_view" name="active_nominations">Active Nominations</h1><div class="clear"></div></ul><div id="active_stream_text_cont"><a id="top_noms" class="awesome large">Top</a><a id="recent_noms" class="awesome large">Most Recent</a></div><div class="clear"></div><div id="profile_cont_wrap"><div id="scroller"><div id="profile_cont"></div></div></div></div>';
$("#wall_cont").append(a);if(t)$("#wall_cont").show();else{$("#wall_cont").a({"max-width":""});$("#wall_cont").s()}R=="top_noms"?$("#top_noms").o("selected"):$("#recent_noms").o("selected")}$("#profile_cont").e();R=="top_noms"?Ea():Bb()}else if(E==="profile"){$("#wall_cont").e();a='<div id="user_profile_cont"><div id="profile_nav_cont" value="albums"><h2>Albums</h2><img id="album_left_arrow" style="display:none;" src="http://s3.amazonaws.com/portrit/img/albumarrow_left.png"/><img id="album_right_arrow" src="http://s3.amazonaws.com/portrit/img/albumarrow.png"/></div><div id="user_profile"></div><div id="album_cont" style="display:none;"></div></div>';
$("#wall_cont").append(a);C="me";mb("me",5,Cb);pb("me");a=a="";if(lb.length>0)for(b=0;b<lb.length;b++)a+='<a href="#/user='+lb[b].id+'" name="'+lb[b].name+'"><img src="https://graph.facebook.com/'+lb[b].id+'/picture?type=square"/></a>';else a="<h3>None of your facebook friends are on Portrit. Send them a invitation by nominating their photos.</h2>";a='<div id="profile_left_cont"><h1>Profile</h1><div id="profile_user_info"><img src="https://graph.facebook.com/'+U.id+'/picture?type=square"/><div id="profile_tab"><h2>Welcome '+
U.name.split(" ")[0]+'</h2></div></div><div id="user_friends"><h2>Friends on Portrit</h2><p class="tooltip"></p>'+a+'</div></div><div id="profile_right_cont"><h2>Your Active Nominations</h2></div><div class="clear"></div>';$("#user_profile").append(a);Db(U.id,Eb);Fb();Gb();if(t)$("#wall_cont").show();else{$("#wall_cont").a({"max-width":""});$("#wall_cont").s(300)}}$("#wall_cont").show();$("#friend_cont").show()}function Db(a,b){$.J("/get_users_active_noms/",{id:a},function(c){b(c)})}
function Eb(a){if(a.length>0){var b="";for(var c=b="",d="",e="",f=0,g=0,h=0;h<a.length;h++){d=a[h].p;e=d.replace(" ","_").toLowerCase();b=a[h].i==U.id?"You":P[a[h].i]==undefined?"":P[a[h].i].name;if(a[h].f==U.id)c=a[h].i==U.id?"Yourself":"You";g=a[h].g.oa/2-25;f=a[h].g.tb/2-38;b='<div class="active_nom_cont nom_cat_'+e+'"><div class="active_nom_cont_left" style="margin-top: '+g+'px;"><a href="/#/user='+a[h].i+'"><img class="active_nom_nominator" src="https://graph.facebook.com/'+a[h].i+'/picture?type=square"/></a><p><a href="/#/user='+
a[h].i+'">'+b+"</a> nominated "+c+' for <span class="strong">'+d+'</span></p></div><a href="/#/nom_id='+a[h].id+'"><p class="active_vote_count nom_cat_'+e+'" style="right: '+f+'px;">Votes: <span class="strong">'+a[h].r+'</span></p><div class="trophy trophy_img small '+e+'"></div><img class="active_nom_photo" src="'+a[h].g.pa+'" style="height: '+a[h].g.oa+"px; width: "+a[h].g.tb+'px;"/></a><div class="clear"></div></div>';$("#profile_right_cont").append(b)}}else $("#profile_right_cont").append("<p>You have no active nominations.</p>")}
function nb(a){if(a.length>0)for(var b=0;b<4;b++){$("#tagged > .img_thumbs").append('<img class="img_thumb img_thumb_'+b+'" id="'+a[b].id+'" src="'+a[b].jb+'"/>');$("#tagged > .album_ajax_loader").remove()}}
function Cb(a){var b=k,c=k,d=0;b="";if(a==undefined)a=0;C!="me"?$("#album_cont").h('<div id="active_cont"><h1>Active Nominations</h1></div><div id="trophy_cont"><h1>Trophy Room</h1></div>'):$("#album_cont").h('<div id="trophy_cont"><h1>Trophy Room</h1></div>');if(K.length>1){$("#album_cont").append("<h1>Facebook Albums</h1>");for(a=a;a<K.length;a++){b='<div class="photo_album" style="display:none;" id="'+K[a].ia.id+'" onclick="void(0)"><div class="img_thumbs"></div><div class="album_title">'+K[a].ia.name+
"</div></div>";$("#album_cont").append(b);c=K[a];b=K[a].ia.id;d=4;if(K[a].u){if(K[a].u.length<d)d=K[a].u.length;for(var e=0;e<d;e++){$("#"+b+" > .img_thumbs").append('<img class="img_thumb img_thumb_'+e+'" id="'+c.u[e].id+'" src="'+c.u[e].jb+'"/>');$("#"+b+" > .album_ajax_loader").remove()}}}}else $("#album_cont").h('<h2 class="alert_title">I\'m sorry. It seems this friend has their photos set to private.</h2>');t?$(".photo_album").show():$(".photo_album").s();t||pb(I().$,Hb)}
function Hb(){var a=0;a="";if(O){if(O.length>0){a='<div class="photo_album" id="video_album"><div class="img_thumbs"></div><div class="album_title">Videos</div></div>';$("#album_cont").append(a);a=4;if(O.length<a)a=O.length;for(var b=0;b<a;b++)$("#video_album > .img_thumbs").append('<img class="img_thumb_'+b+'" id="'+O[b].id+'" src="'+O[b].jb+'"/>')}typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Video_Album","Shown",""])}}
function Ib(a){var b=I().$;if(b!=U.id&&b!="me"&&b!=undefined){b=P[b].name.split(" ")[0];var c="";c="";if(a.F.length>0)for(b=0;b<a.F.length;b++){c=a.F[b].p.replace(" ","_").toLowerCase();c='<div class="active_nom_cont"><div class="active_left_cont nom_cat_'+c+'"></div><div class="active_img_cont"><a href="/#/nom_id='+a.F[b].id+'"><img class="active_nom_image" src="'+a.F[b].g.src+'"/></a></div><div class="active_comment_cont"><a href="/#/nom_id='+a.F[b].id+'"><p>Comments: <span class="strong">'+a.F[b].ja+
'</span></p></a></div><div class="active_vote_cont"><a href="/#/nom_id='+a.F[b].id+'"><p>Votes: <span class="strong">'+a.F[b].r+'</span></p></a></div><div class="active_trophy_img trophy_img medium '+c+'"></div><div class="clear"></div></div>';$("#active_cont").append(c)}else $("#active_cont").append("<h2>"+b+" has no active nominations.")}}
function Jb(a){if(a.Q.length>0){for(var b=4,c="",d={},e=0;e<a.Q.length;e++)if(d[a.Q[e].p]==undefined)d[a.Q[e].p]={noms:[a.Q[e]]};else d[a.Q[e].p].noms.push(a.Q[e]);for(var f in d){a=d[f].noms;c=f.replace(" ","_").toLowerCase();if(a.length<b)b=a.length;album_html='<div class="trophy_album" name="'+f+'" onclick="void(0)"><div class="img_thumbs">';for(e=0;e<b;e++)album_html+='<img class="img_thumb img_thumb_'+e+'"  src="'+a[e].g.pa+'"/>';album_html+='</div><div class="trophy_img large '+c+'"></div><div class="trophy_count nom_cat_'+
c+'">'+a.length+"</div></div>";$("#trophy_cont").append(album_html)}}else{b=I().$;if(b!=undefined&&b!=U.id){b=P[b].name.split(" ")[0];$("#trophy_cont").append("<h2>"+b+" has not won any trophies. Help "+b+" out by nominating a photo.</h2>")}else $("#trophy_cont").append("<h2>You have not won any trophies. Nominate some of your photos for a chance to earn a trophy.</h2>")}}var W={};
function Kb(a){W={};for(var b=0;b<a.length;b++)if(W[a[b].g.Ga]==undefined)W[a[b].g.Ga]=[{fid:a[b].g.da,cat:a[b].p}];else W[a[b].g.Ga].push({fid:a[b].g.da,cat:a[b].p})}
function ob(){var a=I().$;if(a=="me"||a==undefined)a=U.id;if(S[C]==undefined)$.J("/get_user_album_nom_data/",{user:a},function(b){if(b){S[C]=b;Kb(b.Q);for(var c=0;c<b.F.length;c++);if(D=="album"||E==="profile"){Jb(b);Ib(b)}else if(D=="list")W[B]!=undefined&&Lb(W[B]);else D=="gallery"&&W[B]!=undefined&&Lb(W[B])}});else if(D=="album"||E==="profile"){Kb(S[C].Q);Jb(S[C]);Ib(S[C])}else D=="list"&&W[B]!=undefined&&Lb(W[B])}
function Lb(a){for(var b="",c=0;c<a.length;c++){b=a[c].cat.replace(" ","_").toLowerCase();D=="gallery"?$("#"+a[c].fid).parent().append('<div class="trophy_cat trophy_img medium '+b+'"></div>'):$("#"+a[c].fid).parent().a({position:"relative",left:"0px"}).append('<div class="trophy_cat trophy_img medium '+b+'"></div>')}}var X={},Mb={},Y={};
function Nb(a,b){if(typeof b=="undefined")b=k;var c=k,d="",e="",f="",g="",h="",m=g=d="",p=0,y=0,w=0,q=0;d=k;f=0;var j=new Date;var o=h="",s=0;R="top_noms";p=!t||L?690:430;for(var z=0;z<a.length;z++){c=a[z].bc;s=q=0;Y[a[z].R.replace(" ","_").toLowerCase()]=[];if(c.length>0)for(var n=0;n<c.length;n++){m=c[n].p.replace(" ","_").toLowerCase();X[c[n].id]=c[n];y=c[n].g.tb;Y[m].push(c[n].id);y=y>c[n].g.oa?y*(80/c[n].g.oa)+10:80*(y/c[n].g.oa)+10;if(n==0){s=w=p/2-y/2+q;h=f=e=d="";d=new Date(c[n].ka*1E3);f=
j-d;f/=1E3;d=P[c[n].f]?P[c[n].f].name:c[n].f==U.id?"You":"";h="";if(c[n].caption)h="Caption: "+c[n].caption;o="";o=c[n].i==U.id?"You":P[c[n].i].name?P[c[n].i].name:"";for(var A=0;A<c[n].D.length;A++){g=c[n].D[A].tc;e+='<a href="#/user='+c[n].D[A].ga+'" class="clear_profile" id="voted_'+c[n].D[A].ga+'" name="'+g+'"><img src="https://graph.facebook.com/'+c[n].D[A].ga+'/picture?type=square"/></a>'}g='<div class="nom_cat_top_cont nom_cat_'+m+'"><div class="nom_cat_user_cont"><a href="#/user='+c[n].f+
'" class="clear_profile"><img src="https://graph.facebook.com/'+c[n].f+'/picture?type=square"/><h3>'+d+'</h3></a></div><div class="nom_cat_text_cont"><h1>'+c[n].p+'</h1></div><div class="clear"></div></div>';d='<div class="voted_cont"><h3>Voted</h3><p class="tooltip"></p>'+e+"</div>";f='<div class="stream_photo_cont"><div class="nom_cat_stream_cont"><div id="nom_photo_'+c[n].id+'" class="nom_photo_thumbnail" name="selected" style="opacity: 1.0; left:'+w+'px;"><img id="nom_photo_'+c[n].id+'" src="'+
c[n].g.pa+'"/><p class="nom_cat_'+c[n].p.replace(" ","_").toLowerCase()+'">'+Ma(n+1)+'</p></div></div><div class="nom_cat_main_photo_cont"><div class="prev_photo"><div class="prev_photo_img"></div></div><div class="next_photo"><div class="next_photo_img"></div></div><div class="nom_cat_main_photo_wrap"><a href="#/nom_id='+c[n].id+'"><img class="nom_main_photo" src="'+c[n].g.src+'"/></a></div></div><div class="nom_photo_bottom_wrap"><a href="#/user='+c[n].i+'" class="clear_profile"><img class="user_img" src="https://graph.facebook.com/'+
c[n].i+'/picture?type=square"/></a><div class="nominator_cont"><h3>Nominated by <span class="strong"><a href="#/user='+c[n].i+'" class="clear_profile">'+o+'</a></span></h3><p class="caption">'+h+'</p></div><span value="'+c[n].ka*1E3+'">'+J(f)+'</span><a href="#/nom_id='+c[n].id+'"><p class="comments nom_cat_'+m+'">Comments: '+c[n].ja+'</p></a></div><div class="clear"></div></div>';h='<div class="nom_stream_left_cont">'+d+'<div class="clear"></div></div>';message='<div class="feed_post_cont nom_cat_cont_'+
a[z].R.replace(" ","_").toLowerCase()+'" id="nom_'+c[n].id+'">'+g+h+f+'<div class="clear"></div></div>';$("#profile_cont").append(message)}else{w=s+q;e='<div id="nom_photo_'+c[n].id+'" class="nom_photo_thumbnail" style="opacity: 0.6; left:'+w+'px;"><img id="nom_photo_'+c[n].id+'" src="'+c[n].g.pa+'"/><p class="nom_cat_'+c[n].p.replace(" ","_").toLowerCase()+'">'+Ma(n+1)+"</p></div>";$(".nom_cat_stream_cont:last").append(e)}q+=y}else{h=f=e=d=c="";g='<h1 class="nom_cat_'+a[z].R.replace(" ","_").toLowerCase()+
'_text">'+a[z].R+'</h1><div class="clear"></div>';c='<div class="empty_nom_overlay"><div class="empty_message_box"><p>None of your friends are currently nominated for </p><p class="strong">'+a[z].R+'</p><div class="target_message_box"></div></div><div class="empty_trophy trophy_img large '+a[z].R.replace(" ","_").toLowerCase()+'"></div></div>';f='<div class="stream_photo_cont"><div class="nom_cat_stream_cont"></div><div class="nom_cat_main_photo_cont"><div class="nom_cat_main_photo_wrap"></div></div><div class="clear"></div></div>';
h='<div class="nom_stream_left_cont">'+d+'<div class="clear"></div></div>';message='<div class="feed_post_cont empty nom_cat_cont_'+a[z].R.replace(" ","_").toLowerCase()+'">'+c+g+h+f+'<div class="clear"></div></div>';$("#profile_cont").append(message)}}if(C==k||C=="")Ra||(Ra=a);if(D!="main"){z=$("#profile_wrap").outerHeight()+$("#header").height()+$("#main_view_control").outerHeight();$("#friend_album_cont").a({"min-height":z});setTimeout(function(){var T=$("#profile_wrap").outerHeight()+$("#header").height()+
$("#main_view_control").outerHeight();$("#friend_album_cont").a({"min-height":T})},200)}if(t){p=$(".nom_cat_main_photo_cont").X();for(z=0;z<p.length;z++);}}
function Ob(a,b){var c="",d=k;d=I()["recent-winners"]!=undefined?Mb[b]:X[b];$("#nom_photo_"+a).d("name","").a({opacity:0.6});$("#nom_photo_"+b).d("name","selected").a({opacity:1});var e=[],f=0,g=0,h=l,m=$(".nom_cat_stream_cont").width()/2,p=$("#nom_"+a+" .nom_photo_thumbnail");$(p).W(function(){g=$(this).width();if($(this).d("name")==="selected"){f+=g/2;h=i}else if(h===l)f+=g+5;e.push(g+5)});previous_x=0;margin_offset=m-f;$(p).W(function(y){$(this).a({left:previous_x+margin_offset,top:0});previous_x+=
e[y]});$("#nom_"+a+" .voted_cont a").remove();for(m=0;m<d.D.length;m++)c+='<a href="#/user='+d.D[m].ga+'" class="clear_profile" id="voted_'+d.D[m].ga+'" name="'+d.D[m].tc+'"><img src="https://graph.facebook.com/'+d.D[m].ga+'/picture?type=square"/></a>';$("#nom_"+a+" .voted_cont").append(c);$("#nom_"+a+" .nom_main_photo").d("src",d.g.src);$("#nom_"+a+" .nom_cat_user_cont img").d("src","https://graph.facebook.com/"+d.f+"/picture?type=square");$("#nom_"+a+" .nom_cat_user_cont a").d("href","#/user="+
d.f);c="";if(P[d.f])c=P[d.f].name;else if(d.f==U.id)c="You";p=m="";if(d.caption)m="Caption: "+d.caption;p=d.i==U.id?"You":P[d.i]?P[d.i].name:"";$("#nom_"+a+" .nom_cat_user_cont h3").text(c);$("#nom_"+a+" .nom_photo_bottom_wrap > a.clear_profile").d("href","/#/user="+d.i);$("#nom_"+a+" .nom_photo_bottom_wrap img.user_img").d("src","https://graph.facebook.com/"+d.i+"/picture?type=square");$("#nom_"+a+" .nom_photo_bottom_wrap p.comments").text("Comments: "+d.ja).parent().d("href","/#/nom_id="+d.id);
$("#nom_"+a+" .nom_photo_bottom_wrap p.caption").text(m);$("#nom_"+a+" .nom_photo_bottom_wrap .nominator_cont a").d("href","/#/user="+d.i).text(p);$("#nom_"+a+" .vote_cont p").text(d.r);$("#nom_"+a+" .nom_cat_main_photo_wrap a").d("href","/#/nom_id="+d.id);d=new Date-new Date(d.ka*1E3);d/=1E3;$("#nom_"+a+" .nom_photo_bottom_wrap > span").text(J(d));$("#nom_"+a).d("id","nom_"+b)}
function Pb(a){$("#info_loading").e();var b='<div id="profile_info_img"><img id="large_profile_img" src="http://graph.facebook.com/'+a.id+'/picture?type=large"/></div>',c={};c.link=typeof a.link!=="undefined"?a.link:"";c.Da=typeof a.Da!=="undefined"?a.Da:"";c.Ia=typeof a.Ia!=="undefined"?a.Ia:"";c.yb=typeof a.yb!=="undefined"?a.yb:"";c.Qa=typeof a.Qa!=="undefined"?a.Qa:"";c.Ca=typeof a.Ca!=="undefined"?a.Ca:"";c.Wa=typeof a.Wa!=="undefined"?a.Wa:"";c.location=typeof a.Ca!=="undefined"?a.location:
"";c.Ta=typeof a.Ta!=="undefined"?a.Ta:"";c.Ya=typeof a.Ya!=="undefined"?a.Ya:"";c.cb=typeof a.cb!=="undefined"?a.cb:"";c.mb=typeof a.mb!=="undefined"?a.mb:"";c.nb=typeof a.nb!=="undefined"?a.nb:"";c.kb=typeof a.kb!=="undefined"?a.kb:"";b=b;var d="",e="";b+="<ul>";for(key in c)if(c[key]!==""){e="";if(key==="link"){d="Link";e='<a target="_blank" href="'+c[key]+'">Facebook profile</a>'}else if(key==="education"){d="Education";for(var f=0;f<c[key].length;f++)e+="<p>"+c[key][f].Hd.name+"</p>"}else if(key===
"hometown"){d="Hometown";e="<p>"+c[key].name+"</p>"}else{d=key;e=c[key]}b+="<li><h2>"+(d.charAt(0).toUpperCase()+d.slice(1))+" </h2><p>"+e+"</p></li>"}b+="</ul>";Qa=a;$("#info_cont").append(b);$("#info_wrap").append('<h1>Trophy Room</h1><div id="trophy_cont"></div>');a=I().$;c=S[a];b={};d=d=d="";for(d=0;d<c.length;d++)if(b[c[d].ac]==undefined)b[[c[d].ac]]=1;else b[c[d].nom_cat]+=1;for(var g in b)if(g!="undefined"){d=g;d=d.replace(" ","_").toLowerCase();d='<div class="winning_trophy_cont"><a href="/#/trophy/user='+
a+"/trophy="+d+'"><img src="http://s3.amazonaws.com/portrit/img/trophies/medium/'+d+'.png"/><div class="winning_trophy_count nom_cat_'+d+'">'+b[g]+"</div></a></div>";$("#trophy_cont").append(d)}}
function Qb(a,b){if(b=="user_stream"){for(var c=k,d=Ra,e=0;e<d.length;e++){c=d[e].bc;Y[d[e].R.replace(" ","_").toLowerCase()]=[];if(c.length>0)for(var f=0;f<c.length;f++){X[c[f].id]=c[f];Y[c[f].p.replace(" ","_").toLowerCase()].push(c[f].id)}}a&&a(d)}else if(b=="won")$.J("/get_recent_winners/",{nom_id:I().Ad},function(g){for(var h=0;h<g.length;h++)Mb[g[h].id]=g[h];a&&a(g)});else b=="temp"&&$.J("/get_user_win_stream/",function(g){for(var h=0;h<g.length;h++)Mb[g[h].id]=g[h];a&&a(g)})}
function Rb(a,b){b=="light"?$(a).append('<div id="loader"><img src="http://s3.amazonaws.com/portrit/img/ajax-loader-light.gif"/></div>'):$(a).append('<div id="loader"><img src="http://s3.amazonaws.com/portrit/img/album-loader-dark.gif"/></div>')}function Z(){$("#loader").remove()}
function Sb(a){var b=k,c=k,d=k;b=d="";for(var e=0;e<a.length;e++)if(P[a[e].mc])for(var f=0;f<a[e].qa.media.length;f++){b=a[e].qa.media[f];c=b.g.fc;d=a[e].Ab;if(P[d])d=P[d].name;else{d="";for(var g=0;g<a[e].fa.length;g++)if(P[a[e].fa[g]])d=P[a[e].fa[g]].name}b='<div class="new_photo_cont" name="'+d+'" value="'+c+'"><img src="'+b.src+'"/></div>';$("#new_photo_cont").append(b)}$(window).height()<900&&$("#wrapper").a("min-height",900)}var Tb=k;
function Ub(){D="latest_photos";$("#context_overlay_cont > div").append('<div id="new_photo_cont"><h1>Latest Photos</h1><p class="tooltip"></p></div>');Rb($("#context_overlay_cont > div"),"light");if(Tb){Z();Sb(Tb)}else $.J("https://api.facebook.com/method/stream.get?access_token="+G.T+"&limit=50&filter_key="+Xa+"&format=json&callback=?",function(a){Z();Tb=a.gc;Sb(Tb)})}
function Xb(a){var b=k,c="",d=c="";b="";$("#context_overlay_cont > div").append('<div id="new_photo_cont"><h1>Recent Winners</h1></div>');if(a.length>0){for(var e=0;e<a.length;e++){b=a[e].g;c=a[e].p;d=c.replace(" ","_").toLowerCase();c=P[a[e].f]!==undefined?P[a[e].f].name:a[e].f==U.id?"You":"";b='<div class="winning_nom_cont"><a href="/#/nom_id='+a[e].id+'/won/"><img src="'+b.src+'"/></a><div class="winning_nom_overlay"><a href="/#/user='+a[e].f+'"><p class="nom_cat_'+d+'_text">'+c+'</p></a><div class="trophy_img medium '+
d+'"></div></div></div>';$("#new_photo_cont").append(b)}$("#new_photo_cont").append('<div class="clear"></div>')}else $("#new_photo_cont").append("<h2>No Recent Winners.</h2>")}var Yb=k;
function Zb(a){var b=k,c="",d="",e="",f="",g="",h=k,m=new Date,p="",y="",w="",q=w=b="",j="large";if(t&&!L)j="medium";for(var o=0;o<a.length;o++){b=a[o];c=b.p;d=b.p.replace(" ","_").toLowerCase();if(X[b.id]==undefined){X[b.id]=b;if(Y[d])Y[d].push(b.id);else Y[d]=[b.id]}g=P[b.f]?P[b.f].name:b.f==U.id?"You":"";f='<img src="https://graph.facebook.com/'+b.f+'/picture?type=square"/>';e='<img src="'+b.g.src+'"/>';y=p="";if(b.C.length>0){for(q=0;q<b.C.length;q++){w=P[b.C[q].B]?P[b.C[q].B].name:b.C[q].B==
U.id?"You":"";time=new Date(b.C[q].ba*1E3);h=m-time;h/=1E3;p+='<div class="comment"><p class="comment_time" value="'+b.C[q].ba+'">'+J(h)+'</p><a href="#/user='+b.C[q].B+'"><img class="user_photo" src="https://graph.facebook.com/'+b.C[q].B+'/picture?type=square"/></a><a href="#/user='+b.C[q].B+'" class="post_username from_username clear_profile">'+w+"</a><p>"+b.C[q].sa+"</p></div>"}if(b.xd)y='<p class="load_more_comments" value="'+b.id+'">Load more comments</p>'}else p='<div class="comment_empty"><h2>No comments yet. Be the first!</h2></div>';
q="";w=b.i==U.id?"You":P[b.i]?P[b.i].name:"";if(b.caption)q=b.caption;time=new Date(b.ka*1E3);h=m-time;h/=1E3;b='<div class="recent_nom_cont" value="'+b.id+'" time="'+b.ka+'"><div class="recent_nom_top_cont nom_cat_'+d+'"><a href="#/user='+b.f+'">'+f+'</a><a href="#/user='+b.f+'"><h2>'+g+'</h2></a><h3>Nominated for <a href="#/trophy='+d+'"><span class="strong">'+c+"</span></a><span>"+J(h)+'</span></h3><div class="clear"></div></div><div class="recent_nom_photo_cont"><div class="recent_nom_photo_left_cont"><div class="recent_nom_photo_left_wrap"><a href="#/nom_id='+
b.id+'">'+e+'<div id="nominator_overlay_cont"><a href="/#/user='+b.i+'"><img class="user_img" src="https://graph.facebook.com/'+b.i+'/picture?type=square"/></a><h2>Nominated by <span class="strong"><a href="/#/user='+b.i+'">'+w+"</a></span></h2><p>"+q+'</p></div></a></div></div><div class="recent_nom_photo_right_cont"><div class="recent_nom_vote_count nom_vote_'+b.id+'"><div class="trophy_img '+j+" "+d+'"></div><a href="#/nom_id='+b.id+'/votes"><h2 class="nom_cat_'+d+'">Votes: <span class="strong">'+
b.r+'</span></h2></a></div><div class="clear"></div></div><div class="clear"></div></div><div class="recent_nom_comment_cont" id="nom_comments_'+b.id+'"><div class="recent_nom_comment_heading" value="'+b.id+'"><a href="#/nom_id='+b.id+'/comments"><h1>Comments</h1></a><span class="add_new_comment awesome large">New Comment</span><div class="clear"></div></div>'+p+y+'<div class="clear"></div></div></div>';$("#recent_left_cont").append(b)}a.length>=10&&$("#recent_left_cont").append('<div id="load_more_noms_cont"><span id="load_more" class="awesome large">Load More</span></div>')}
function $b(){var a="";Rb($("#recent_empty_wrap > .empty_cont"),"light");Qb(function(c){Z();var d=k,e="",f=e="";d="";var g=8;if(c.length>0){$("#recent_empty_wrap > h3").U("<p>These photos just won.</p>");if(c.length<g)g=c.length;for(var h=0;h<g;h++){d=c[h].g;e=c[h].p;e=e.replace(" ","_").toLowerCase();f=P[c[h].f]!==undefined?P[c[h].f].name:c[h].f==U.id?"You":"";d='<div class="winning_nom_cont"><a href="/#/nom_id='+c[h].id+'/won/"><img src="'+d.src+'"/></a><div class="winning_nom_overlay"><a href="/#/user='+
c[h].f+'"><p class="nom_cat_'+e+'_text">'+f+'</p></a><div class="trophy_img medium '+e+'"></div></div></div>';$("#recent_empty_wrap > .empty_cont").append(d)}$("#recent_empty_wrap > .empty_cont").append('<div class="clear"></div>')}else{$("#recent_empty_wrap > h3").U("<h1>No Recent Winners.</h1>");$("#recent_empty_wrap > h3").U("<p>These photos just won.</p>")}},"won");a='<div id="empty_noms_cont"><h1>There are no <span class="strong">Active Nominations</span></h1><h2>Help us make this a happenin\' place and nominate your friends photos.</h2><div id="search_empty_wrap"><div id="empty_search_cont"><ul><li><p>1. Find your friends.</p></li><li><p>2. Nominate their best photos.</p></li><li><p>3. Vote on your favorite.</p></li></ul><input id="empty_search" type="text" value="Find your Friends"/><div id="clear_empty_search" class="close_img mobile" style="display:none;" onclick="void(0)"></div></div><div class="empty_cont"></div></div><div id="recent_empty_wrap"><h3>Recent Winners</h3><div class="empty_cont"></div></div><div id="latest_empty_wrap"><h3>Latest Photos</h3><p>The newest photos on Facebook.</p><div class="empty_cont"></div></div></div>';
$("#scroller").append(a);Rb($("#latest_empty_wrap > .empty_cont"),"light");$.J("https://api.facebook.com/method/stream.get?access_token="+G.T+"&limit=50&filter_key="+Xa+"&format=json&callback=?",function(c){Z();a:{c=c.gc;for(var d=0,e=0;e<c.length;e++)for(var f=0;f<c[e].qa.media.length;f++)if(P[c[e].mc]){photo=c[e].qa.media[f];photo_id=photo.g.fc;owner_id=c[e].Ab;if(P[owner_id])owner_name=P[owner_id].name;else{owner_name="";for(var g=0;g<c[e].fa.length;g++)if(P[c[e].fa[g]])owner_name=P[c[e].fa[g]].name}photo_html=
'<div class="new_photo_cont" name="'+owner_name+'" value="'+photo_id+'"><img src="'+photo.src+'"/></div>';$("#latest_empty_wrap > .empty_cont").append(photo_html);d+=1;if(d==6){t||$("#latest_empty_wrap > .empty_cont").append('<p class="tooltip"></p>');break a}}}});$("#empty_search").L("focus, blur, keyup");$("#clear_empty_search").L("click");$("#empty_search").H("focus",function(){F=i;$(this).a("color","#333");if(this.value==this.defaultValue)this.value="";this.value!=this.defaultValue&&this.select()});
$("#empty_search").H("blur",function(){F=l;$(this).a("color","#888");if($.wb(this.value)=="")this.value=this.defaultValue?this.defaultValue:""});$("#clear_empty_search").H("click",function(){$("#empty_search").q("").Z("keyup").Z("blur")});var b=[];for(a=0;a<Q.length;a++)Q[a].Rb===l&&b.push(Q[a].name);$("#empty_search").H("keyup",function(){var c=$(this).q(),d,e,f,g;if(c==""){$("#empty_search_cont").a({"-webkit-border-radius":"10px","-moz-border-radius":"10px","-webkit-box-shadow":"none","-moz-box-shadow":"none",
padding:"15px"});$("#search_empty_wrap .empty_cont").a({padding:"0px"}).h("");$("#clear_empty_search").e()}else{$("#clear_empty_search").show();e=b.length;d=[];c=c.toLowerCase();for(g=0;g<e;g++){f=b[g];f.toLowerCase().indexOf(c)===0&&d.push(f)}$("#search_empty_wrap .empty_cont").h("");if(d.length>0){$("#search_empty_wrap .empty_cont").a({padding:"10px 10px"});$("#empty_search_cont").a({"-webkit-border-bottom-left-radius":"0px","-webkit-border-bottom-right-radius":"0px","-moz-border-radius-bottomleft":"0px",
"-moz-border-radius-bottomruight":"0px","-webkit-box-shadow":"rgba(0, 0, 0, 0.496094) 0px 9px 3px -4px","-moz-box-shadow":"0 9px 3px -4px rgba(0, 0, 0, 0.5)","padding-bottom":"0px"});c=k;c=f=e="";for(g=0;g<d.length;g++){a:{for(c=0;c<Q.length;c++)if(Q[c].name==d[g]){c=Q[c].id;break a}c=k}c=P[c];e='<div class="crop"><img class="friend_pic" src="https://graph.facebook.com/'+c.id+'/picture?type=large"/></div>';f='<div class="text_wrapper"><div class="text" onclick="void(0)"><h3>'+c.name+"</h3></div></div>";
c='<div class="friend" name="'+c.name+'" value="'+c.id+'" onclick="void(0)"><div class="img_cont">'+e+f+"</div></div>";$("#search_empty_wrap .empty_cont").append(c)}}else $("#search_empty_wrap .empty_cont").h("<h1>No friend's with first name starting in: "+c+"</h1>")}});$(".new_photo_cont").c("mouseover mouseout",function(c){c.type=="mouseover"?ac(this):bc(this)});yb()}
function cc(){L&&$("#profile_wrap").a({width:"960px",right:"0px"});$("#active_stream_view").e();$("#active_stream_text_cont").e();$("#tab_nav").e()}function dc(){L&&$("#profile_wrap").a({width:"940px",right:"20px"});$("#active_stream_view").show();$("#active_stream_text_cont").show();$("#tab_nav").show()}
function Bb(){Rb($("#scroller"),"light");$("#profile_cont").append('<div id="recent_cont_1"><div id="recent_left_cont"></div><div id="top_right_cont"></div></div><div class="clear"></div>');$.J("/init_recent_stream/",function(a){Z();R="recent_noms";if(a.kc.length>0){dc();Zb(a.kc);if(!t||L){$("#top_right_cont").hc('<h1>Time <span class="strong">Remaining</strong></h1><h2 id="time_countdown"></h2></h1>');dateNow=new Date;amount=dateFuture.getTime()-dateNow.getTime();delete dateNow;if(amount<0){dateFuture=
new Date(2011,0,(new Date).getDate(),24,0,0);tzOffset=-8;V=dateFuture.toGMTString();V=V.substr(0,V.length-3);tzCurrent=dateFuture.getTimezoneOffset()/60*-2;dateFuture.setTime(Date.parse(V));dateFuture.setHours(dateFuture.getHours()+tzCurrent-tzOffset);$("#cont").append('<div id="winners_announced_cont"><h2>Winners are being calculated. Check back in a few minutes.</h2></div>')}secs=mins=hours=days=0;out="";amount=Math.floor(amount/1E3);days=Math.floor(amount/86400);amount%=86400;hours=Math.floor(amount/
3600);amount%=3600;mins=Math.floor(amount/60);amount%=60;secs=Math.floor(amount);if(days!=0||hours!=0)out+=hours+"h:";if(days!=0||hours!=0||mins!=0)out+=mins+"m:";out+=secs+"s";$("#time_countdown").text(out);setTimeout("GetCount()",1E3);var b=a.top,c=k,d="",e="",f="",g="";c="";var h=5;$("#top_right_cont").append('<h1>The Daily <span class="strong">Leaderboard</h1>');if(b.length<h)h=b.length;for(var m=0;m<b.length;m++){c=b[m];d=c.p.replace(" ","_").toLowerCase();if(X[c.id]==undefined){X[c.id]=c;if(Y[d])Y[d].push(c.id);
else Y[d]=[c.id]}if(m<h){g=P[c.f]?P[c.f].name:c.f==U.id?"You":"";e='<img src="https://graph.facebook.com/'+c.f+'/picture?type=square"/>';f='<img src="'+c.g.pa+'"/>';c='<div class="top_nom_cont"><a href="#/user='+c.f+'"><h2>'+g+'</h2></a><div class="top_nom_wrap"><div class="top_nom_left_cont nom_cat_'+d+'"><a href="#/user='+c.f+'" name="'+g+'">'+e+'</a><p class="vote_count">'+Ma(m+1)+'</p></div><div class="top_nom_right_cont"><a href="#/nom_id='+c.id+'">'+f+'</a></div><div class="clear"></div><div class="top_nom_bottom_cont"><div class="top_nom_comment_cont nom_comment_'+
c.id+'"><a href="#/nom_id='+c.id+'"><p>Comments: <span class="strong">'+c.ja+'</span></p></a></div><div class="top_nom_vote_count nom_vote_'+c.id+'"><a href="#/nom_id='+c.id+'"><p>Votes: <span class="strong">'+c.r+'</span></p></a></div><div class="clear"></div></div></div></div>';$("#top_right_cont").append(c)}}a=a.Pd;h=b="";if(a.length>0){h='<h1>All Time <span class="strong">Leaderboard</span></h1><div id="top_friends">';for(m=0;m<a.length;m++){b='<div class="top_friend"><p class="nom_cat_'+a[m].Od.replace(" ",
"_").toLowerCase()+'">'+Ma(m+1)+'</p><a href="/#/user='+a[m].da+'"><h2>'+P[a[m].da].name+'</h2></a><a href="/#/user='+a[m].da+'"><img src="https://graph.facebook.com/'+a[m].da+'/picture?type=square"/></a></div>';h+=b}h+="</div>";$("#top_right_cont").append(h)}}$("#profile_cont").show()}else{$b();cc()}})}dateFuture=new Date(2011,0,(new Date).getDate(),24,0,0);tzOffset=-8;V=dateFuture.toGMTString();V=V.substr(0,V.length-3);tzCurrent=dateFuture.getTimezoneOffset()/60*-2;dateFuture.setTime(Date.parse(V));
dateFuture.setHours(dateFuture.getHours()+tzCurrent-tzOffset);function Ea(){if($("#profile_cont").l().length===0)if(Ra.length==0){cc();$b()}else{dc();Nb(Ra);$("#profile_cont").show()}}function Ha(){var a=I().$;if(Qa===k)FB.aa("/"+a+"/",function(b){Pb(b)});else $("#profile_info_img").length==0&&Pb(Qa)}
function Ia(){D="info";var a=$("#friend_album_cont").width();$("#friend_album_cont").jc([]).stop();$("#info_wrap").show();a=$("#info_wrap").height()+50;if(a<400)a=600;$("#friend_album_cont").a({"min-height":a,height:""});a=$("#info_wrap").outerWidth()+30;if(t){$("#album_cont").a({opacity:"0.5"});$("#friend_album_cont").a({left:a})}else{$("#album_cont").Ra(0.45,0.5);$("#friend_album_cont").G({left:a},450,"easeOutCubic");$("#album_cont").c("click",function(){$("#user_photo_view").click()})}Pa=k;typeof _gaq!==
"undefined"&&_gaq.push(["_trackEvent","Info","Shown",""])}
function Fa(){D="profile";var a=$("#friend_album_cont").width();$("#friend_album_cont").jc([]).stop();$("#profile_wrap").show();a=-($("#profile_wrap").outerWidth()+35);if(t){L&&$("#album_cont").a({opacity:"0.5"});$("#friend_album_cont").a({left:a})}else{$("#album_cont").Ra(0.45,0.5);$("#friend_album_cont").G({left:a},450,"easeOutCubic");$("#album_cont").c("click",function(){$("#user_photo_view").click()})}a=$("#profile_wrap").outerHeight()+$("#header").height()+$("#main_view_control").outerHeight();
$("#friend_album_cont").a({"min-height":a});Pa=k;typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Profile","Shown",""])}
function Ga(){D="album";clearInterval(Wa);$("#friend_album_cont").height();$("#friend_album_cont").width();$("#album_cont").show();var a=$("#album_cont").height()+50;if(a<400)a=600;$("#friend_album_cont").a({height:a,"min-height":""});if(t){if(L){$("#album_cont").a({opacity:"1.0"});$("#friend_album_cont").a({left:"0px"});$("#profile_wrap").e();$("#info_wrap").e()}else{$("#profile_wrap").e();$("#info_wrap").e();$("#friend_album_cont").show();$("#friend_album_cont").a({left:"0px"});$("#album_cont").a({opacity:"1.0"})}$("#profile_cont").h("")}else{$("#album_cont").Ra("fast",
1);$("#friend_album_cont").G({left:"0px"},450,"easeOutCubic",function(){$("#profile_wrap").e();$("#info_wrap").e();$("#profile_cont").h("")});$("#album_cont").b("click")}}var ec=k;
function ac(a){clearTimeout(ec);$(".tooltip:visible").a({top:"0px",opacity:"0"});var b=$(a).d("name");if(b!=""){$(a).outerHeight();var c=$(a).position().left+($(a).outerWidth()-$(".tooltip").width())/2-4,d=$(a).position().top-30;$(a).parent().find(".tooltip").text(b).a({top:d,left:c,width:"150px",opacity:"1.0","z-index":"100"})}}function bc(a){$(a).parent().find(".tooltip").a({opacity:"0","z-index":"-1"})}
function fc(){var a=$(this).d("value"),b=this;$.J("/get_nom_comments/",{nom_id:a},function(c){if(X[a])X[a].A=c;var d=$("#nom_comments_"+a);$(d).find(".comment").remove();for(var e="",f="",g=k,h=k,m=0;m<c.length;m++){e=P[c[m].A.B]!=undefined?P[c[m].A.B].name:c[m].A.B==U.id?"You":"";h=new Date;g=new Date(c[m].A.ba*1E3);h-=g;h/=1E3;f+='<div class="comment"><p class="comment_time" value="'+c[m].A.ba+'">'+J(parseInt(h))+'</p><a href="#/user='+c[m].A.B+'" class="clear_profile"><img class="user_photo" src="https://graph.facebook.com/'+
c[m].A.B+'/picture?type=square"/></a><a href="#/user='+c[m].A.B+'" class="post_username from_username clear_profile">'+e+"</a><p>"+c[m].A.sa+"</p></div>"}$(d).find(".recent_nom_comment_heading").U(f);$(b).remove()})}function gc(){var a=$(this).v().v();$(a).a({"min-height":""});var b=$(a).l().length-2;$(a).l().filter(":lt("+b+")").remove();$(this).text("Load More Comments").n("hide_more_comments").o("load_more_comments")}
function hc(){var a='<div class="comment_form_cont" style="display: none;"><div class="comment_top_head"><a class="submit_comment awesome large" name="'+$(this).d("value")+'">Post</a><a class="cancel_comment awesome large">Close</a></div><textarea id="new_comment_body" class="comment_body"></textarea></div></div>';if($(this).parent().find(".comment_form_cont").length==0){$(this).parent().append(a);a=$(this).parent();t===l?$(a).find(".comment_form_cont").Jd(function(){$(this).find(".comment_body").focus()}):
$(a).find(".comment_form_cont").show().find(".comment_body").focus();$(this).e();$(this).next().Va("load_more_comments")&&$(this).next().e()}}function ic(){var a=$(this).parent().parent();if(t){$(a).v().show();$(a).v().v().show();$(a).remove()}else $(a).Kd(function(){$(a).v().show();$(a).v().v().show();$(this).remove()});return l}
function jc(){var a=$(this).d("name"),b=$(this).parent().parent(),c=$(this).parent().next().q();if(D==="gallery"){if(c!=""){$("#cancel_photo_comment").click();$("#photo_comment_body").q("");$("#photo_comments").show();M[a]=M[a]&&typeof M[a]==="object"&&typeof M[a].length==="number"&&typeof M[a].splice==="function"&&!M[a].propertyIsEnumerable("length")?M[a].concat({fromid:U.id,text:c}):[{fromid:U.id,text:c}];var d='<div class="photo_comment comment" style="display:none;"><img class="user_photo" src="http://graph.facebook.com/'+
U.id+'/picture?type=square"/><p>'+c+"</p></div>";$("#photo_comments").append(d);$("#photo_comments").l().filter(".photo_comment:last").s();$.P("https://api.facebook.com/method/comments.add?text="+c+"&object_id="+a+"&publish_to_stream=true&access_token="+G.T,{text:c,object_id:a,publish_to_stream:"true",T:G.T},r());F=l}}else if(D==="profile"||D=="main")c!=""&&$(this).parent().parent().ca("fast",function(){$("#photo_comments").show();var e='<div class="comment_self" style="display:none;"><div class="like" name="Like"><img style="display: none; " class="like_photo" src="http://s3.amazonaws.com/portrit/img/like.png"></div><a href="#/user=me"><img class="user_photo" src="http://graph.facebook.com/'+
U.id+'/picture?type=square"></a><p>'+c+"</p></div>",f=$(b).parent().l().filter(".post_comments");if(f.length===0){e='<div class="post_comments">'+e+"</div>";$(b).parent().append(e);$(b).parent().find(".comment_self").s()}else{$(f).append(e);$(f).l().td().s()}e=$(b).v().Db();$(b).v().remove();$.P("https://graph.facebook.com/"+a+"/comments",{access_token:G.T,message:c},r());$(b).parent().append(e);$(b).parent().l().filter(".add_comment_peek").s();$(b).remove();$(this).remove();F=l});return l}
function kc(){Ua=i;Ta=l;N=[];var a=Na==undefined?$(Oa).l():$(Na).l(),b=[-55,90,-55,90],c=[-70,-70,75,75];$(a).W(function(d){var e=b[d];d=c[d];var f=k,g="";g=$(this).a("-webkit-transform");var h=$(this).a("-moz-transform");if(g!==k)f=g;else if(h!==k)f=h;g="translate("+e+"px, "+d+"px)";$(this).a({"-moz-transform":g,"-webkit-transform":g,"z-index":Sa});Sa+=1;N.push({photo:this,rot:f})});$(a).parent().next().a("z-index",100);typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Peek","Shown",""])}
function yb(){$(".friend").c("click",function(){if(E=="wall"){var a=$(this).d("value");window.location.href="/#/user="+a}else{a=$(".alpha_key_wall",this).text();window.location.href="/#/alpha_key="+a}})}function lc(a,b){$("#nom_vote_count").text(b.r);if(S[b.f])for(var c=S[b.f].F,d=0;d<c.length;d++)if(a==c[d].id)c[d].r=b.r}
function mc(){var a=this,b=$(this).d("value");if($(this).Va("won")==l){$.P("/vote/",{method:"up",nomination_id:b},function(c){if(c){var d=$(a).parent().l().filter("p");$(d).text(c.r);if(X[b]){X[b].r=c.r;X[b].D.push({vote_user:U.id,vote_name:U.name})}d='<a href="#/user='+U.id+'" class="clear_profile" id="voted_'+U.id+'" name="'+U.name+'"><img src="https://graph.facebook.com/'+U.id+'/picture?type=square"/></a>';if(D=="nom_detail"){$("#nom_votes_wrap").append(d);$(".vote").o("won")}else $("#nom_"+b+
" .voted_cont").append(d);lc(b,c)}});typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Vote","Up",""])}}
function nc(){var a=this,b=$(this).d("value");if($(this).Va("won")==l){$.P("/vote/",{method:"down",nomination_id:b},function(c){if(c){var d=$(a).parent().l().filter("p");$(d).text(c.r);if(X[b]){X[b].r=c.r;X[b].D.push({vote_user:U.id,vote_name:U.name})}d='<a href="#/user='+U.id+'" class="clear_profile" id="voted_'+U.id+'" name="'+U.name+'"><img src="https://graph.facebook.com/'+U.id+'/picture?type=square"/></a>';if(D=="nom_detail"){$("#nom_votes_wrap").append(d);$(".vote").o("won")}else $("#nom_"+
b+" .voted_cont").append(d);lc(b,c)}});typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Vote","Down",""])}}$("#close_overlay").c("click",oc);
function oc(){$("#tab_nav > .selected").n("selected");if(t){$("#wrapper").a("opacity",1);$("#context_overlay").e();$("#context_overlay_cont").n();$("#context_overlay_cont > div").h("")}else{$("#wrapper").G({opacity:1},300);$("#context_overlay").ca(function(){$("#context_overlay_cont").n();$("#context_overlay_cont > div").h("")})}$("#wrapper").a("min-height","")}
function pc(a){$("#close_overlay").n().o("close_img "+H);if(t){typeof a!=="undefined"&&$("#wrapper").a("opacity",0.3);$("#context_overlay").show()}else{typeof a!=="undefined"&&$("#wrapper").G({opacity:0.3},300);$("#context_overlay").s()}$("#context_overlay").a("top",150)}var qc=l;
function Ab(){$(".clear_profile").c("click",function(){qc=i});$(".submit_comment").c("click",jc);$(".add_comment_peek").c("click",hc);$(".load_more_comments").c("click",fc);$(".hide_more_comments").c("click",gc);$(".cancel_comment").c("click",ic);$(".photo_post img").c("click",function(){var a=$(this).d("aid"),b=$(this).d("pid"),c=$(this).d("owner");$("#photo_list").h("");K=k;x=b;B=a;C=c;Ba()});$(".photo_post a").c("click",function(){$("#photo_list").h("");K=k});$(".nom_photo_thumbnail").c("click",
function(){if($(this).d("name")==undefined||$(this).d("name")!="selected"){var a=$(this).d("id").replace("nom_photo_",""),b=$(this).parent().l().filter('.nom_photo_thumbnail[name="selected"]').d("id").replace("nom_photo_","");$(this).parent().parent().find(".vote_up, .vote_down").d("name",a);Ob(b,a)}});$(".vote_up").c("click",mc);$(".vote_down").c("click",nc);$("#activate_latest_photos").c("click",function(){$("#tab_nav > .selected").n("selected");$(this).o("selected");$("#context_overlay_cont").n().o("latest_photos_overlay");
pc();Ub();typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Latest Photos","Shown",""])});$("#activate_recent_winners").c("click",function(){$("#tab_nav > .selected").n("selected");$(this).o("selected");$("#context_overlay_cont").n().o("latest_photos_overlay");pc();D="recent_winners";Rb($("#context_overlay_cont > div"),"light");if(Yb){Z();Xb(Yb)}else{Z();Qb(Xb,"won")}typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Recent Winners","Shown",""])});$(".voted_cont a, .new_photo_cont").c("mouseover mouseout",
function(a){a.type=="mouseover"?ac(this):bc(this)});$(".new_photo_cont").c("click",function(){var a=$(this).d("value");$("#photo_list").h("");$.J("https://api.facebook.com/method/photos.get?access_token="+G.T+"&pids="+a+"&format=json&callback=?",function(b){b=b[0];var c=b.Dd,d=b.yc;x=String(b.Bd);window.location.href="#/user="+c+"/album="+d+"/gallery";$("#close_overlay").click()})});$(".next_photo").c("click",function(){var a=$(this).parent().v().l().filter('[name="selected"]');$(a).next().click()});
$(".prev_photo").c("click",function(){var a=$(this).parent().v().l().filter('[name="selected"]');$(a).v().click()});$(".add_new_comment").c("click",function(){var a='<div class="new_comment_cont" style="display:none;"><div class="comment_top_head"><a class="awesome large post_new_comment" value="'+$(this).parent().d("value")+'">Post</a><a class="awesome large cancel_new_comment">Close</a></div><textarea class="comment_body"></textarea></div>';$(this).parent().U(a);$(this).e();$(this).parent().parent().find(".new_comment_cont").show();
$(this).parent().parent().find(".comment_body").focus();typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Comment","Shown",""])});$(".cancel_new_comment").c("click",function(){var a=$(this).parent().parent();$(a).parent().find(".add_new_comment").show();$(a).remove()});$(".post_new_comment").c("click",function(){var a=$(this).parent().parent(),b=$(a).find(".comment_body").q().replace(/\n\r?/g,"<br />"),c=$(this).d("value"),d='<div class="comment" style="display:none;"><p class="comment_time" value="'+
(new Date).getTime()/1E3+'">Right now</p><a href="#/user='+U.id+'" class="clear_profile"><img class="user_photo" src="https://graph.facebook.com/'+U.id+'/picture?type=square"/></a><a href="#/user='+U.id+'" class="post_username from_username clear_profile">You</a><p>'+b+"</p></div>";$(a).U(d);$(a).U(d);$(a).next().s();$(a).find(".cancel_new_comment").click();$(a).find(".comment_body").q("");$(a).parent().find(".comment_empty").remove();$.P("/new_comment/",{body:b,nom_id:c},function(e){if(e){e=JSON.parse(e);
X[c].ja+=1;X[c].A&&X[c].A.unshift({comments:{comment:e.M.sa,id:e.M.Eb,owner_id:e.M.Fb,owner_name:e.M.Gb,create_datetime:e.M.ba}});X[c].C.unshift({comments:{comment:e.M.sa,id:e.M.Eb,owner_id:e.M.Fb,owner_name:e.M.Gb,create_datetime:e.M.ba}});var f=new Date,g=k;$(".comment_time").W(function(){time=new Date($(this).d("value")*1E3);g=f-time;g/=1E3;$(this).text(J(parseInt(g)))})}});typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Comment","Posted",""])});$(".comment_body").c("focus",function(){F=i});
$(".comment_body").c("blur",function(){F=l});$("#load_more").c("click",function(){var a=$(".recent_nom_cont:last").d("time");$(this).remove();$("#recent_left_cont").append('<div id="profile_loading"><img src="http://s3.amazonaws.com/portrit/img/ajax-loader-light.gif"/></div>');$.J("/get_more_recent_stream/",{create_time:a},function(b){$("#profile_loading").remove();Zb(b)});typeof _gaq!=="undefined"&&_gaq.push(["_trackEvent","Stream","Load More",""])})}
function Gb(){$("#user_friends a").c("mouseover mouseout",function(a){a.type=="mouseover"?ac(this):bc(this)});$("#profile_nav_cont").c("click",function(){if($(this).d("value")=="albums"){$(window).width();$(".photo_album");var a=$("#album_cont").height(),b=$("#profile_nav_cont");$(b).d("value","trophies");$("h2",b).text("Profile");$("#album_right_arrow").e();$("#album_left_arrow").show();$("#album_cont").show();$("#user_profile_cont").a({"min-height":a});if(t)if(L)$("#user_profile_cont").a({right:"800px"});
else{$("#profile_nav_cont").a({right:"-100px"});$("#user_profile_cont").a({right:"520px"})}else $("#user_profile_cont").G({right:"800px"},300)}else{a=$("#profile_nav_cont");$(a).d("value","albums");$("h2",a).text("Albums");$("#album_right_arrow").show();$("#album_left_arrow").e();$("#user_profile_cont").a({"min-height":""});if(t){L||$("#profile_nav_cont").a({right:"10px"});$("#user_profile_cont").a({right:"0px"})}else $("#user_profile_cont").G({right:"0px"},300)}})}
function Fb(){if(!t){$(".img_thumbs").c("mousedown",function(a){Na=this;Ta=l;Pa=setTimeout(kc,200);a.stopPropagation();return l});$(document).H("mouseup",function(){for(var a=0;a<N.length;a++){var b=N[a].g,c=N[a].Gd;Ua=l;Ta=i;$(b).a({"-moz-transform":c,"-webkit-transform":c})}$(b).parent().next().a("z-index",1001);N=[];clearTimeout(Pa)})}$(".winning_trophy_cont").c("mouseover mouseout",function(a){a.type=="mouseover"?$(".winning_trophy_count",this).a("opacity","1"):$(".winning_trophy_count",this).a("opacity",
"0.8")});$("#user_info_view").c("click",function(){if(D!="info"){Ha();Ia()}});$("#user_photo_view").c("click",function(){D!="album"&&Ga()});$("#user_wall_view").c("click",function(){if(D!="profile"){Ea();Fa()}});$(".photo_album").c("click",function(){if(!Ua&&!Ta){$("#photo_list").h("");x="";B=$(this).d("id");Ba()}});$(".photo_album").c("mouseover mouseout",function(a){a.type=="mouseover"?$(this).l(".album_title").a("background-color","#222"):$(this).l(".album_title").a("background-color","#444")});
$(".trophy_album").c("click",function(){var a=$(this).d("name").replace(" ","_").toLowerCase(),b=I().$;if(!b)b=U.id;window.location.href="/#/trophy/user="+b+"/trophy="+a})}
function xb(){$(".img_thumbs").b("click");$(".img_thumbs").b("mousedown");$(".clear_profile").b("click");$(".photo_thumbs").b("click");$("#clear_db").b("click");$("#allow_notifications").b("click");$(".friend").b("click");$(".alpha_key_wall").b("click");$(".friend").b("mousedown");$(".profile_link").b("click");$(".photo_album").b("click");$("#load_more").b("click");$("#user_info_view").b("click");$("#user_photo_view").b("click");$("#user_wall_view").b("click");$(".comment, .comment_self").b("mouseover");
$(".comment, .comment_self").b("mouseout");$(".add_comment_peek").b("click");$(".cancel_comment").b("click");$(".comment_body").b("focus");$(".comment_body").b("blur");$(".upgrade_tooltip_cont").b("mouseover");$(".upgrade_tooltip_cont").b("mouseout");$(".load_more_comments").b("click");$(".hide_more_comments").b("click");$("#profile_cont_wrap").L("scroll");$(".photo_post a").b("click");$(".photo_post img").b("click");$(".vote_up").b("click");$(".vote_down").b("click");$(".nom_photo_thumbnail").b("click");
$("#profile_wrap  > ul > h1").b("mouseover mouseout");$("#activate_latest_photos").b("click");$("#activate_recent_winners").b("click");$(".voted_cont a, .new_photo_cont").b("mouseover mouseout");$(".new_photo_cont").b("click");$(".next_photo").b("click");$(".prev_photo").b("click");$("#close_upload, #cancel_upload").b("click");$("#show_upload").b("click");$(".kill_photo").b("click");$(".photo_caption").b("focus");$(".photo_caption").b("blur");$("#profile_nav_cont").b("click");$(".add_new_comment").b("click");
$(".comment_body").b("focus");$(".comment_body").b("blur");$(".cancel_new_comment").b("click");$(".post_new_comment").b("click");$("#user_friends img").b("mouseover mouseout");$("#post_upload").b("click");$("#upload_photo_button").b("change");$(".winning_trophy_cont").b("mouseover mouseout");$(".trophy_album").b("click");$(".nom_photo_thumbnail").b("click");$("#add_new_comment").b("click");$(".post_new_comment").b("click");$(".photo_thumbs").b("mousedown");$(window).L("scroll");if(t){$("#back_gallery, #back_gallery_mobile").b("touchend");
$("#forward_gallery, #forward_gallery_mobile").b("touchend")}else{$("#back_gallery, #back_gallery_mobile").b("click");$("#forward_gallery, #forward_gallery_mobile").b("click")}$(".like_photo").b("click");$("#photo_large_inline_cont").b("click");$("#nominate_photo").b("click");$("#go_nom_detail").b("click");$("#cancel_nominate_photo, #cancel_nomination").b("click");$("#new_nomination_cont li").b("click");$("#nomination_comment").b("focus");$("#nomination_comment").b("blur");$("#post_nomination").b("click");
$(".kill_nomination").b("click");$("#close_nom_success").b("click");if(t){$(".img_thumbs").b("touchstart");$(".img_thumbs").b("touchend");document.body.removeEventListener("touchmove",fb);document.body.removeEventListener("touchend",gb);document.body.removeEventListener("touchstart",hb)}$(document).L("mouseup")}
function wb(a){$("#wall_cont").h("");$("#canvas_cont").h("");$("#context_cont").h("");$("#friend_album_cont").h("");$(".photos_loading").remove();a.wd||$("#main_view_control").remove();$("#profile_wrap").remove();if(qc){$(window).L("scroll");$("#profile_cont").h("");$("#album_cont").h("");Qa=k;qc=l}F=l;$("#photo_list").a({"padding-top":"0","margin-bottom":"0"});$("#photo_cont").a({"min-height":""});$("#friend_album_cont").a({height:"","min-height":"","max-width":""});$("#right_quick_nav").e();$("#left_quick_nav").e();
$("#context_cont").e();$("#new_nomination_wrap").e();$("#title").e();$("#title").h("");$("#top").e();$("#login_loader").e();if(a.ld===undefined&&a.ia===undefined||a.Cc!==undefined)$("#photo_cont").e()}
jQuery.extend({Ib:function(a,b){var c="jUploadFrame"+a;if(window.vc){var d=document.createElement('<iframe id="'+c+'" name="'+c+'" />');if(typeof b=="boolean")d.src="javascript:false";else if(typeof b=="string")d.src=b}else{d=document.createElement("iframe");d.id=c;d.name=c}d.style.position="absolute";d.style.top="-1000px";d.style.left="-1000px";document.body.appendChild(d);return d},Hb:function(a,b){var c="jUploadForm"+a,d="jUploadFile"+a;c=$('<form  action="" method="POST" name="'+c+'" id="'+c+
'" enctype="multipart/form-data"></form>');var e=$("#"+b),f=$(e).Db();$(e).d("id",d);$(e).Ac(f);$(e).Ha(c);$(c).a("position","absolute");$(c).a("top","-1200px");$(c).a("left","-1200px");$(c).Ha("body");return c},wc:function(a){function b(m){var p=document.getElementById(e);try{if(p.contentWindow){g.responseText=p.contentWindow.document.body?p.contentWindow.document.body.innerHTML:k;g.responseXML=p.contentWindow.document.XMLDocument?p.contentWindow.document.XMLDocument:p.contentWindow.document}else if(p.contentDocument){g.responseText=
p.contentDocument.document.body?p.contentDocument.document.body.innerHTML:k;g.responseXML=p.contentDocument.document.XMLDocument?p.contentDocument.document.XMLDocument:p.contentDocument.document}}catch(y){jQuery.handleError(a,g,k,y)}if(g||m=="timeout"){f=i;var w;try{w=m!="timeout"?"success":"error";if(w!="error"){var q=jQuery.qc(g,a.dataType);a.nc&&a.nc(q,w);a.global&&jQuery.event.Z("ajaxSuccess",[g,a])}else jQuery.handleError(a,g,w)}catch(j){w="error";jQuery.handleError(a,g,w,j)}a.global&&jQuery.event.Z("ajaxComplete",
[g,a]);a.global&&!--jQuery.zb&&jQuery.event.Z("ajaxStop");a.complete&&a.complete(g,w);jQuery(p).L();setTimeout(function(){try{$(p).remove();$(d).remove()}catch(o){jQuery.handleError(a,g,k,o)}},100);g=k}}a=jQuery.extend({},jQuery.xc,a);var c=(new Date).getTime(),d=jQuery.Hb(c,a.jd);jQuery.Ib(c,a.Id);var e="jUploadFrame"+c;c="jUploadForm"+c;a.global&&!jQuery.zb++&&jQuery.event.Z("ajaxStart");var f=l,g={};a.global&&jQuery.event.Z("ajaxSend",[g,a]);a.timeout>0&&setTimeout(function(){f||b("timeout")},
a.timeout);try{d=$("#"+c);$(d).d("action",a.url);$(d).d("method","POST");$(d).d("target",e);if(d.encoding)d.encoding="multipart/form-data";else d.enctype="multipart/form-data";$(d).submit()}catch(h){jQuery.handleError(a,g,k,h)}window.attachEvent?document.getElementById(e).attachEvent("onload",b):document.getElementById(e).addEventListener("load",b,l);return{abort:r()}},qc:function(a,b){var c=!b;c=b=="xml"||c?a.responseXML:a.responseText;b=="script"&&jQuery.md(c);b=="json"&&eval("data = "+c);b=="html"&&
jQuery("<div>").h(c).fd();return c}});